// Command genfunc writes func_gen.go: the Type of Lean functions of 1 to 15 parameters (the
// wire format's limit) as Go functions.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/genfunc; DO NOT EDIT.\n\npackage lungo\n\nimport \"encoding/binary\"\n")
	for n := 1; n <= 15; n++ {
		var params, typeParams, fields, ctorArgs, ctorInit, exprs, decodes, callArgs, encodes []string
		for i := 1; i <= n; i++ {
			params = append(params, fmt.Sprintf("A%d", i))
			typeParams = append(typeParams, fmt.Sprintf("A%d", i))
			fields = append(fields, fmt.Sprintf("a%d Type[A%d]", i, i))
			ctorArgs = append(ctorArgs, fmt.Sprintf("a%d Type[A%d]", i, i))
			ctorInit = append(ctorInit, fmt.Sprintf("a%d", i))
			exprs = append(exprs, fmt.Sprintf("out = append(out, t.a%d.Expr()...)", i))
			decodes = append(decodes, fmt.Sprintf("x%d, err := t.a%d.Decode(r)\nif err != nil {\nreturn err\n}", i, i))
			callArgs = append(callArgs, fmt.Sprintf("x%d", i))
			encodes = append(encodes, fmt.Sprintf("if err := t.a%d.Encode(w, x%d); err != nil {\nreturn err\n}", i, i))
		}
		all := strings.Join(typeParams, ", ") + ", R"
		fn := fmt.Sprintf("func(%s) (R, error)", strings.Join(params, ", "))
		var sig []string
		for i := 1; i <= n; i++ {
			sig = append(sig, fmt.Sprintf("x%d A%d", i, i))
		}
		fmt.Fprintf(&b, `
type func%[1]dType[%[2]s any] struct {
	%[3]s
	r Type[R]
}

// Func%[1]dType is the Lean function type of %[1]d parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func%[1]dType[%[2]s any](%[4]s, r Type[R]) Type[%[5]s] {
	return func%[1]dType[%[2]s]{%[6]s, r}
}

func (t func%[1]dType[%[2]s]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, %[1]d)
	%[7]s
	return append(out, t.r.Expr()...)
}

func (t func%[1]dType[%[2]s]) Encode(w *Writer, f %[5]s) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		%[8]s
		res, err := f(%[9]s)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func%[1]dType[%[2]s]) Decode(r *Reader) (%[5]s, error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(%[10]s) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			%[11]s
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}
`, n, all, strings.Join(fields, "\n"), strings.Join(ctorArgs, ", "), fn, strings.Join(ctorInit, ", "),
			strings.Join(exprs, "\n"), strings.Join(decodes, "\n"), strings.Join(callArgs, ", "), strings.Join(sig, ", "),
			strings.Join(encodes, "\n"))
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile("func_gen.go", src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
