// Code generated by internal/genfunc; DO NOT EDIT.

package lungo

import "encoding/binary"

type func1Type[A1, R any] struct {
	a1 Type[A1]
	r  Type[R]
}

// Func1Type is the Lean function type of 1 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func1Type[A1, R any](a1 Type[A1], r Type[R]) Type[func(A1) (R, error)] {
	return func1Type[A1, R]{a1, r}
}

func (t func1Type[A1, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 1)
	out = append(out, t.a1.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func1Type[A1, R]) Encode(w *Writer, f func(A1) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func1Type[A1, R]) Decode(r *Reader) (func(A1) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func2Type[A1, A2, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	r  Type[R]
}

// Func2Type is the Lean function type of 2 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func2Type[A1, A2, R any](a1 Type[A1], a2 Type[A2], r Type[R]) Type[func(A1, A2) (R, error)] {
	return func2Type[A1, A2, R]{a1, a2, r}
}

func (t func2Type[A1, A2, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 2)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func2Type[A1, A2, R]) Encode(w *Writer, f func(A1, A2) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func2Type[A1, A2, R]) Decode(r *Reader) (func(A1, A2) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func3Type[A1, A2, A3, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	r  Type[R]
}

// Func3Type is the Lean function type of 3 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func3Type[A1, A2, A3, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], r Type[R]) Type[func(A1, A2, A3) (R, error)] {
	return func3Type[A1, A2, A3, R]{a1, a2, a3, r}
}

func (t func3Type[A1, A2, A3, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 3)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func3Type[A1, A2, A3, R]) Encode(w *Writer, f func(A1, A2, A3) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func3Type[A1, A2, A3, R]) Decode(r *Reader) (func(A1, A2, A3) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func4Type[A1, A2, A3, A4, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	a4 Type[A4]
	r  Type[R]
}

// Func4Type is the Lean function type of 4 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func4Type[A1, A2, A3, A4, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], r Type[R]) Type[func(A1, A2, A3, A4) (R, error)] {
	return func4Type[A1, A2, A3, A4, R]{a1, a2, a3, a4, r}
}

func (t func4Type[A1, A2, A3, A4, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 4)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func4Type[A1, A2, A3, A4, R]) Encode(w *Writer, f func(A1, A2, A3, A4) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func4Type[A1, A2, A3, A4, R]) Decode(r *Reader) (func(A1, A2, A3, A4) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func5Type[A1, A2, A3, A4, A5, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	a4 Type[A4]
	a5 Type[A5]
	r  Type[R]
}

// Func5Type is the Lean function type of 5 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func5Type[A1, A2, A3, A4, A5, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], r Type[R]) Type[func(A1, A2, A3, A4, A5) (R, error)] {
	return func5Type[A1, A2, A3, A4, A5, R]{a1, a2, a3, a4, a5, r}
}

func (t func5Type[A1, A2, A3, A4, A5, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 5)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func5Type[A1, A2, A3, A4, A5, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func5Type[A1, A2, A3, A4, A5, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func6Type[A1, A2, A3, A4, A5, A6, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	a4 Type[A4]
	a5 Type[A5]
	a6 Type[A6]
	r  Type[R]
}

// Func6Type is the Lean function type of 6 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func6Type[A1, A2, A3, A4, A5, A6, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6) (R, error)] {
	return func6Type[A1, A2, A3, A4, A5, A6, R]{a1, a2, a3, a4, a5, a6, r}
}

func (t func6Type[A1, A2, A3, A4, A5, A6, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 6)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func6Type[A1, A2, A3, A4, A5, A6, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func6Type[A1, A2, A3, A4, A5, A6, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func7Type[A1, A2, A3, A4, A5, A6, A7, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	a4 Type[A4]
	a5 Type[A5]
	a6 Type[A6]
	a7 Type[A7]
	r  Type[R]
}

// Func7Type is the Lean function type of 7 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func7Type[A1, A2, A3, A4, A5, A6, A7, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7) (R, error)] {
	return func7Type[A1, A2, A3, A4, A5, A6, A7, R]{a1, a2, a3, a4, a5, a6, a7, r}
}

func (t func7Type[A1, A2, A3, A4, A5, A6, A7, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 7)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func7Type[A1, A2, A3, A4, A5, A6, A7, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func7Type[A1, A2, A3, A4, A5, A6, A7, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func8Type[A1, A2, A3, A4, A5, A6, A7, A8, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	a4 Type[A4]
	a5 Type[A5]
	a6 Type[A6]
	a7 Type[A7]
	a8 Type[A8]
	r  Type[R]
}

// Func8Type is the Lean function type of 8 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func8Type[A1, A2, A3, A4, A5, A6, A7, A8, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8) (R, error)] {
	return func8Type[A1, A2, A3, A4, A5, A6, A7, A8, R]{a1, a2, a3, a4, a5, a6, a7, a8, r}
}

func (t func8Type[A1, A2, A3, A4, A5, A6, A7, A8, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 8)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func8Type[A1, A2, A3, A4, A5, A6, A7, A8, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func8Type[A1, A2, A3, A4, A5, A6, A7, A8, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func9Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, R any] struct {
	a1 Type[A1]
	a2 Type[A2]
	a3 Type[A3]
	a4 Type[A4]
	a5 Type[A5]
	a6 Type[A6]
	a7 Type[A7]
	a8 Type[A8]
	a9 Type[A9]
	r  Type[R]
}

// Func9Type is the Lean function type of 9 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func9Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error)] {
	return func9Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, r}
}

func (t func9Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 9)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func9Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func9Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func10Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R any] struct {
	a1  Type[A1]
	a2  Type[A2]
	a3  Type[A3]
	a4  Type[A4]
	a5  Type[A5]
	a6  Type[A6]
	a7  Type[A7]
	a8  Type[A8]
	a9  Type[A9]
	a10 Type[A10]
	r   Type[R]
}

// Func10Type is the Lean function type of 10 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func10Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], a10 Type[A10], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) (R, error)] {
	return func10Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, r}
}

func (t func10Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 10)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	out = append(out, t.a10.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func10Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		x10, err := t.a10.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func10Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9, x10 A10) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			if err := t.a10.Encode(w, x10); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func11Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R any] struct {
	a1  Type[A1]
	a2  Type[A2]
	a3  Type[A3]
	a4  Type[A4]
	a5  Type[A5]
	a6  Type[A6]
	a7  Type[A7]
	a8  Type[A8]
	a9  Type[A9]
	a10 Type[A10]
	a11 Type[A11]
	r   Type[R]
}

// Func11Type is the Lean function type of 11 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func11Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], a10 Type[A10], a11 Type[A11], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11) (R, error)] {
	return func11Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, r}
}

func (t func11Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 11)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	out = append(out, t.a10.Expr()...)
	out = append(out, t.a11.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func11Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		x10, err := t.a10.Decode(r)
		if err != nil {
			return err
		}
		x11, err := t.a11.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func11Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9, x10 A10, x11 A11) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			if err := t.a10.Encode(w, x10); err != nil {
				return err
			}
			if err := t.a11.Encode(w, x11); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func12Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R any] struct {
	a1  Type[A1]
	a2  Type[A2]
	a3  Type[A3]
	a4  Type[A4]
	a5  Type[A5]
	a6  Type[A6]
	a7  Type[A7]
	a8  Type[A8]
	a9  Type[A9]
	a10 Type[A10]
	a11 Type[A11]
	a12 Type[A12]
	r   Type[R]
}

// Func12Type is the Lean function type of 12 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func12Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], a10 Type[A10], a11 Type[A11], a12 Type[A12], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12) (R, error)] {
	return func12Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, r}
}

func (t func12Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 12)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	out = append(out, t.a10.Expr()...)
	out = append(out, t.a11.Expr()...)
	out = append(out, t.a12.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func12Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		x10, err := t.a10.Decode(r)
		if err != nil {
			return err
		}
		x11, err := t.a11.Decode(r)
		if err != nil {
			return err
		}
		x12, err := t.a12.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func12Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9, x10 A10, x11 A11, x12 A12) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			if err := t.a10.Encode(w, x10); err != nil {
				return err
			}
			if err := t.a11.Encode(w, x11); err != nil {
				return err
			}
			if err := t.a12.Encode(w, x12); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func13Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R any] struct {
	a1  Type[A1]
	a2  Type[A2]
	a3  Type[A3]
	a4  Type[A4]
	a5  Type[A5]
	a6  Type[A6]
	a7  Type[A7]
	a8  Type[A8]
	a9  Type[A9]
	a10 Type[A10]
	a11 Type[A11]
	a12 Type[A12]
	a13 Type[A13]
	r   Type[R]
}

// Func13Type is the Lean function type of 13 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func13Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], a10 Type[A10], a11 Type[A11], a12 Type[A12], a13 Type[A13], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13) (R, error)] {
	return func13Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, r}
}

func (t func13Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 13)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	out = append(out, t.a10.Expr()...)
	out = append(out, t.a11.Expr()...)
	out = append(out, t.a12.Expr()...)
	out = append(out, t.a13.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func13Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		x10, err := t.a10.Decode(r)
		if err != nil {
			return err
		}
		x11, err := t.a11.Decode(r)
		if err != nil {
			return err
		}
		x12, err := t.a12.Decode(r)
		if err != nil {
			return err
		}
		x13, err := t.a13.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func13Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9, x10 A10, x11 A11, x12 A12, x13 A13) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			if err := t.a10.Encode(w, x10); err != nil {
				return err
			}
			if err := t.a11.Encode(w, x11); err != nil {
				return err
			}
			if err := t.a12.Encode(w, x12); err != nil {
				return err
			}
			if err := t.a13.Encode(w, x13); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func14Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R any] struct {
	a1  Type[A1]
	a2  Type[A2]
	a3  Type[A3]
	a4  Type[A4]
	a5  Type[A5]
	a6  Type[A6]
	a7  Type[A7]
	a8  Type[A8]
	a9  Type[A9]
	a10 Type[A10]
	a11 Type[A11]
	a12 Type[A12]
	a13 Type[A13]
	a14 Type[A14]
	r   Type[R]
}

// Func14Type is the Lean function type of 14 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func14Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], a10 Type[A10], a11 Type[A11], a12 Type[A12], a13 Type[A13], a14 Type[A14], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14) (R, error)] {
	return func14Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, r}
}

func (t func14Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 14)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	out = append(out, t.a10.Expr()...)
	out = append(out, t.a11.Expr()...)
	out = append(out, t.a12.Expr()...)
	out = append(out, t.a13.Expr()...)
	out = append(out, t.a14.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func14Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		x10, err := t.a10.Decode(r)
		if err != nil {
			return err
		}
		x11, err := t.a11.Decode(r)
		if err != nil {
			return err
		}
		x12, err := t.a12.Decode(r)
		if err != nil {
			return err
		}
		x13, err := t.a13.Decode(r)
		if err != nil {
			return err
		}
		x14, err := t.a14.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func14Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9, x10 A10, x11 A11, x12 A12, x13 A13, x14 A14) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			if err := t.a10.Encode(w, x10); err != nil {
				return err
			}
			if err := t.a11.Encode(w, x11); err != nil {
				return err
			}
			if err := t.a12.Encode(w, x12); err != nil {
				return err
			}
			if err := t.a13.Encode(w, x13); err != nil {
				return err
			}
			if err := t.a14.Encode(w, x14); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}

type func15Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R any] struct {
	a1  Type[A1]
	a2  Type[A2]
	a3  Type[A3]
	a4  Type[A4]
	a5  Type[A5]
	a6  Type[A6]
	a7  Type[A7]
	a8  Type[A8]
	a9  Type[A9]
	a10 Type[A10]
	a11 Type[A11]
	a12 Type[A12]
	a13 Type[A13]
	a14 Type[A14]
	a15 Type[A15]
	r   Type[R]
}

// Func15Type is the Lean function type of 15 parameters, as a Go function. A Go function
// passed to Lean may run on any thread; its error is fatal to the Lean program, since Lean's
// functions cannot fail. A Lean function returned to Go fails only with a MalformedError.
func Func15Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R any](a1 Type[A1], a2 Type[A2], a3 Type[A3], a4 Type[A4], a5 Type[A5], a6 Type[A6], a7 Type[A7], a8 Type[A8], a9 Type[A9], a10 Type[A10], a11 Type[A11], a12 Type[A12], a13 Type[A13], a14 Type[A14], a15 Type[A15], r Type[R]) Type[func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15) (R, error)] {
	return func15Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R]{a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, r}
}

func (t func15Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R]) Expr() []byte {
	out := []byte{tagFunction}
	out = binary.LittleEndian.AppendUint32(out, 15)
	out = append(out, t.a1.Expr()...)
	out = append(out, t.a2.Expr()...)
	out = append(out, t.a3.Expr()...)
	out = append(out, t.a4.Expr()...)
	out = append(out, t.a5.Expr()...)
	out = append(out, t.a6.Expr()...)
	out = append(out, t.a7.Expr()...)
	out = append(out, t.a8.Expr()...)
	out = append(out, t.a9.Expr()...)
	out = append(out, t.a10.Expr()...)
	out = append(out, t.a11.Expr()...)
	out = append(out, t.a12.Expr()...)
	out = append(out, t.a13.Expr()...)
	out = append(out, t.a14.Expr()...)
	out = append(out, t.a15.Expr()...)
	return append(out, t.r.Expr()...)
}

func (t func15Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R]) Encode(w *Writer, f func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15) (R, error)) error {
	if f == nil {
		return malformed("a nil function")
	}
	w.hostFunction(func(r *Reader, w *Writer) error {
		x1, err := t.a1.Decode(r)
		if err != nil {
			return err
		}
		x2, err := t.a2.Decode(r)
		if err != nil {
			return err
		}
		x3, err := t.a3.Decode(r)
		if err != nil {
			return err
		}
		x4, err := t.a4.Decode(r)
		if err != nil {
			return err
		}
		x5, err := t.a5.Decode(r)
		if err != nil {
			return err
		}
		x6, err := t.a6.Decode(r)
		if err != nil {
			return err
		}
		x7, err := t.a7.Decode(r)
		if err != nil {
			return err
		}
		x8, err := t.a8.Decode(r)
		if err != nil {
			return err
		}
		x9, err := t.a9.Decode(r)
		if err != nil {
			return err
		}
		x10, err := t.a10.Decode(r)
		if err != nil {
			return err
		}
		x11, err := t.a11.Decode(r)
		if err != nil {
			return err
		}
		x12, err := t.a12.Decode(r)
		if err != nil {
			return err
		}
		x13, err := t.a13.Decode(r)
		if err != nil {
			return err
		}
		x14, err := t.a14.Decode(r)
		if err != nil {
			return err
		}
		x15, err := t.a15.Decode(r)
		if err != nil {
			return err
		}
		res, err := f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15)
		if err != nil {
			return &HostError{Message: "a Go function passed to Lean failed: " + err.Error()}
		}
		return t.r.Encode(w, res)
	})
	return nil
}

func (t func15Type[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R]) Decode(r *Reader) (func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15) (R, error), error) {
	h, err := r.leanFunction()
	if err != nil {
		return nil, err
	}
	p, expr := r.program, t.Expr()
	return func(x1 A1, x2 A2, x3 A3, x4 A4, x5 A5, x6 A6, x7 A7, x8 A8, x9 A9, x10 A10, x11 A11, x12 A12, x13 A13, x14 A14, x15 A15) (R, error) {
		var res R
		err := callClosure(p, h, expr, func(w *Writer) error {
			if err := t.a1.Encode(w, x1); err != nil {
				return err
			}
			if err := t.a2.Encode(w, x2); err != nil {
				return err
			}
			if err := t.a3.Encode(w, x3); err != nil {
				return err
			}
			if err := t.a4.Encode(w, x4); err != nil {
				return err
			}
			if err := t.a5.Encode(w, x5); err != nil {
				return err
			}
			if err := t.a6.Encode(w, x6); err != nil {
				return err
			}
			if err := t.a7.Encode(w, x7); err != nil {
				return err
			}
			if err := t.a8.Encode(w, x8); err != nil {
				return err
			}
			if err := t.a9.Encode(w, x9); err != nil {
				return err
			}
			if err := t.a10.Encode(w, x10); err != nil {
				return err
			}
			if err := t.a11.Encode(w, x11); err != nil {
				return err
			}
			if err := t.a12.Encode(w, x12); err != nil {
				return err
			}
			if err := t.a13.Encode(w, x13); err != nil {
				return err
			}
			if err := t.a14.Encode(w, x14); err != nil {
				return err
			}
			if err := t.a15.Encode(w, x15); err != nil {
				return err
			}
			return nil
		}, func(r *Reader) error {
			v, err := t.r.Decode(r)
			res = v
			return err
		})
		return res, err
	}, nil
}
