// Package lungo is the Go support library of lungo's generated packages: the lungo runtime
// (linked once per binary), the wire format between Go and the runtime, Lean values that
// have no Go counterpart, and errors.
//
// A package generated by `lungo generate --go_out` compiles its Lean program's C with cgo and
// calls it through this package. Its functions take and return Go values: Nat and Int are
// *big.Int, structures are structs, inductive types are sealed interfaces with one struct per
// constructor, polymorphic functions take a Type for each type parameter.
//
// The runtime library is linked from lib/<goos>_<goarch>/ of this module, which the lungo
// release fills for every supported platform.
package lungo

//go:generate go run ./internal/genfunc

/*
#cgo CFLAGS: -I${SRCDIR}/include
#include "lungo.h"

extern int32_t lungoGoDispatch(uint64_t callback, uint8_t *input, size_t len, lungo_buffer *out);
extern void lungoGoRetain(uint64_t callback);
extern void lungoGoRelease(uint64_t callback);

static void lungo_go_install_host(void) {
	lungo_set_host((lungo_host_dispatch)lungoGoDispatch, lungoGoRetain, lungoGoRelease);
}
*/
import "C"

func init() {
	C.lungo_go_install_host()
}

// ABIVersion is the C ABI of the runtime this package links.
const ABIVersion = C.LUNGO_ABI_VERSION
