//! The native layer of `LeanOracle` mode: the facade calls Lean's natively compiled functions
//! through FFI, and facade conversions allocate through Lean's C runtime.

use super::GenInput;
use super::compiler::{rust_params, rust_type};
use super::syntax::string;
use crate::CodegenError;
use crate::core::names::mangle;
use crate::core::writer::Writer;
use lungo_bir::{Declaration, IrType};
use std::collections::HashMap;

fn symbols<'a>(input: &'a GenInput) -> HashMap<&'a str, &'a str> {
    input.success.oracle.symbols.iter().map(|s| (s.name.as_str(), s.symbol.as_str())).collect()
}

fn symbol<'a>(syms: &HashMap<&str, &'a str>, name: &str) -> Result<&'a str, CodegenError> {
    syms.get(name).copied().ok_or_else(|| CodegenError::internal(format!("no native symbol for {name}")))
}

fn declaration<'a>(input: &'a GenInput, name: &str) -> Result<&'a Declaration, CodegenError> {
    input
        .success
        .bir
        .declaration(name)
        .ok_or_else(|| CodegenError::internal(format!("{name} is not part of the program")))
}

/// An FFI declaration of the natively compiled `decl` under its Rust (mangled) name.
fn ffi_function(w: &mut Writer, decl: &Declaration, sym: &str) {
    let params: Vec<String> =
        rust_params(&decl.params).iter().map(|p| format!("x_{}: {}", p.var, rust_type(p.ty))).collect();
    w.line(format!("#[link_name = {}]", string(sym)));
    w.line(format!("pub(crate) fn {}({}) -> {};", mangle(&decl.name), params.join(", "), rust_type(decl.result)));
}

/// Emits the contents of `__lng` for `LeanOracle` mode: FFI declarations of the exported
/// functions and the native module initialization.
pub fn emit_native_layer(w: &mut Writer, input: &GenInput) -> Result<(), CodegenError> {
    let syms = symbols(input);
    let mut exports: Vec<&Declaration> = Vec::new();
    for e in &input.success.interface.exports {
        exports.push(declaration(input, &e.name)?);
    }
    if let Some(entry) = &input.success.entry_point {
        exports.push(declaration(input, &entry.declaration)?);
    }
    w.open("unsafe extern \"C\" {");
    for d in &exports {
        let sym = symbol(&syms, &d.name)?;
        if d.params.is_empty() {
            // Nullary declarations are global variables initialized by the module initializer.
            w.line(format!("#[link_name = {}]", string(sym)));
            w.line(format!("static S_{}: {};", mangle(&d.name), rust_type(d.result)));
        } else {
            ffi_function(w, d, sym);
        }
    }
    for (i, init) in input.success.oracle.module_initializers.iter().enumerate() {
        w.line(format!("#[link_name = {}]", string(&init.symbol)));
        w.line(format!("fn module_init_{i}(builtin: u8) -> Obj;"));
    }
    w.line("fn lean_io_mark_end_initialization();");
    w.line("fn lean_init_task_manager();");
    w.close("}");
    w.line("");
    for d in &exports {
        if d.params.is_empty() {
            w.line("#[inline]");
            w.open(format!("pub(crate) unsafe extern \"C\" fn {}() -> {} {{", mangle(&d.name), rust_type(d.result)));
            w.line(format!("unsafe {{ S_{} }}", mangle(&d.name)));
            w.close("}");
        }
    }
    w.line("");
    w.line("/// Initializes Lean's runtime and the root modules' native code once.");
    w.open("pub fn __initialize() {");
    w.line("static INIT: ::std::sync::Once = ::std::sync::Once::new();");
    w.open("INIT.call_once(|| unsafe {");
    // Every module initializer first initializes Lean's runtime (`lean_initialize_runtime_module`,
    // or `lean_initialize` for users of the `Lean` package), as Lean's C emitter generates them;
    // the shim's external class can only be registered afterwards. The sequence follows the
    // `main` Lean's C emitter generates.
    for (i, init) in input.success.oracle.module_initializers.iter().enumerate() {
        w.line(format!("let r = module_init_{i}(1);"));
        w.open("if rt::lean_ptr_tag(r) != 0 {");
        w.line(
            "let msg = <super::__oracle::Backend as ::lungo::Backend>::io_error_to_string(rt::lean_ctor_get(r, 0));",
        );
        w.line(format!(
            "panic!(\"initialization of Lean module {} failed: uncaught exception: {{msg}}\");",
            init.module
        ));
        w.close("}");
        w.line("<super::__oracle::Backend as ::lungo::Backend>::dec(r);");
    }
    w.line("super::__oracle::initialize_shim();");
    w.line("lean_io_mark_end_initialization();");
    w.line("lean_init_task_manager();");
    w.close("});");
    w.close("}");
    Ok(())
}

/// The C shim compiled with Lean's headers: `lean.h` implements allocation and reference
/// counting as inline functions, which the oracle backend reaches through these wrappers.
pub const C_SHIM: &str = r#"// Generated by lungo for LeanOracle mode. Do not edit.
#include <lean/lean.h>
/* lean.h declares `malloc` and `free`; Lean's toolchain compiler ships no C library headers. */

lean_object * lng_oracle_alloc_ctor(unsigned tag, unsigned num_objs, size_t scalar_size) {
    return lean_alloc_ctor(tag, num_objs, (unsigned)scalar_size);
}
void lng_oracle_inc(lean_object * o) { lean_inc(o); }
void lng_oracle_dec(lean_object * o) { lean_dec(o); }
lean_object * lng_oracle_alloc_array(size_t size, size_t capacity) { return lean_alloc_array(size, capacity); }
lean_object * lng_oracle_alloc_sarray(unsigned elem_size, size_t size, size_t capacity) {
    return lean_alloc_sarray(elem_size, size, capacity);
}
lean_object * lng_oracle_alloc_closure(void * fun, unsigned arity, unsigned num_fixed) {
    return lean_alloc_closure(fun, arity, num_fixed);
}

typedef struct {
    void * data;
    void (*finalize)(void *);
} lng_external;

static void lng_external_finalize(void * p) {
    lng_external * e = (lng_external *)p;
    e->finalize(e->data);
    free(e);
}

static void lng_external_foreach(void * p, b_lean_obj_arg f) { (void)p; (void)f; }

static lean_external_class * g_lng_external_class = NULL;

void lng_oracle_initialize_shim(void) {
    if (g_lng_external_class == NULL) {
        g_lng_external_class = lean_register_external_class(lng_external_finalize, lng_external_foreach);
    }
}

lean_object * lng_oracle_alloc_external(void * data, void (*finalize)(void *)) {
    lng_external * e = (lng_external *)malloc(sizeof(lng_external));
    if (e == NULL) lean_internal_panic_out_of_memory();
    e->data = data;
    e->finalize = finalize;
    return lean_alloc_external(g_lng_external_class, e);
}

void * lng_oracle_external_data(lean_object * o) {
    return ((lng_external *)lean_get_external_data(o))->data;
}
"#;

/// Whether the `idx`-th parameter of `decl` is borrowed.
fn borrowed(decl: &Declaration, idx: usize) -> bool {
    decl.params.get(idx).is_some_and(|p| p.borrow)
}

/// Emits the contents of `__oracle`: the C-runtime backend and the native `main` runner.
pub fn emit_backend(w: &mut Writer, input: &GenInput) -> Result<(), CodegenError> {
    let syms = symbols(input);
    let helpers = [
        ("nat_repr", "Nat.reprFast"),
        ("int_repr", "Int.repr"),
        ("io_error_to_string", "IO.Error.toString"),
        ("io_user_error", "IO.userError"),
    ];
    let mut owned_arg = HashMap::new();
    for (_, lean) in helpers {
        let d = declaration(input, lean)?;
        let params = rust_params(&d.params);
        if params.len() != 1 || !params[0].ty.is_object() || !d.result.is_object() {
            return Err(CodegenError::internal(format!("{lean} does not have an object → object signature")));
        }
        owned_arg.insert(lean, !borrowed(d, 0));
    }
    w.line("use ::lungo::__runtime::{self as rt, Obj};");
    w.line("");
    w.open("unsafe extern \"C\" {");
    for line in [
        "fn lng_oracle_alloc_ctor(tag: u32, num_objs: u32, scalar_size: usize) -> Obj;",
        "fn lng_oracle_inc(o: Obj);",
        "fn lng_oracle_dec(o: Obj);",
        "fn lng_oracle_alloc_array(size: usize, capacity: usize) -> Obj;",
        "fn lng_oracle_alloc_sarray(elem_size: u32, size: usize, capacity: usize) -> Obj;",
        "fn lng_oracle_alloc_closure(fun: *const (), arity: u32, num_fixed: u32) -> Obj;",
        "fn lng_oracle_initialize_shim();",
        "fn lng_oracle_alloc_external(data: *mut (), finalize: unsafe extern \"C\" fn(*mut ())) -> Obj;",
        "fn lng_oracle_external_data(o: Obj) -> *mut ();",
        "fn lean_mark_mt(o: Obj);",
        "fn lean_mk_string_from_bytes(s: *const u8, size: usize) -> Obj;",
        "fn lean_cstr_to_nat(s: *const ::core::ffi::c_char) -> Obj;",
        "fn lean_cstr_to_int(s: *const ::core::ffi::c_char) -> Obj;",
        "fn lean_apply_n(f: Obj, n: u32, args: *mut Obj) -> Obj;",
        "fn lean_finalize_task_manager();",
    ] {
        w.line(line);
    }
    for (rust, lean) in helpers {
        w.line(format!("#[link_name = {}]", string(symbol(&syms, lean)?)));
        w.line(format!("fn {rust}(o: Obj) -> Obj;"));
    }
    w.close("}");
    w.line("");
    w.line("pub(crate) unsafe fn initialize_shim() {");
    w.line("    unsafe { lng_oracle_initialize_shim() }");
    w.line("}");
    w.line("");
    // Calls a helper, retaining the argument first when the helper consumes it.
    let call = |rust: &str, lean: &str, arg: &str| -> String {
        if owned_arg[lean] { format!("{{ lng_oracle_inc({arg}); {rust}({arg}) }}") } else { format!("{rust}({arg})") }
    };
    w.line("/// Lean's runtime and the program's modules are initialized before the backend creates any");
    w.line("/// object: Rust values can be converted to Lean before the first facade call.");
    w.line("#[inline]");
    w.line("fn ready() {");
    w.line("    super::__lng::__initialize();");
    w.line("}");
    w.line("");
    w.line("/// Lean's C runtime.");
    w.line("pub enum Backend {}");
    w.line("");
    w.open("unsafe fn read_string(s: Obj) -> ::std::string::String {");
    w.line("unsafe {");
    w.line("    let out = rt::lean_string_str(s).to_owned();");
    w.line("    lng_oracle_dec(s);");
    w.line("    out");
    w.line("}");
    w.close("}");
    w.line("");
    w.open("unsafe impl ::lungo::Backend for Backend {");
    w.line("unsafe fn alloc_ctor(tag: u32, num_objs: u32, scalar_size: usize) -> Obj { ready(); unsafe { lng_oracle_alloc_ctor(tag, num_objs, scalar_size) } }");
    w.line("unsafe fn inc(o: Obj) { unsafe { lng_oracle_inc(o) } }");
    w.line("unsafe fn dec(o: Obj) { unsafe { lng_oracle_dec(o) } }");
    w.line("unsafe fn mark_mt(o: Obj) { unsafe { lean_mark_mt(o) } }");
    w.line("fn mk_string(s: &str) -> Obj { ready(); unsafe { lean_mk_string_from_bytes(s.as_ptr(), s.len()) } }");
    w.open("fn nat_from_big(v: &::lungo::__num_bigint::BigUint) -> Obj {");
    w.line("ready();");
    w.line("let s = ::std::ffi::CString::new(v.to_string()).expect(\"decimal digits\");");
    w.line("unsafe { lean_cstr_to_nat(s.as_ptr()) }");
    w.close("}");
    w.open("unsafe fn nat_to_big(o: Obj) -> ::lungo::__num_bigint::BigUint {");
    w.line(format!("let s = unsafe {{ read_string({}) }};", call("nat_repr", "Nat.reprFast", "o")));
    w.line("s.parse().unwrap_or_else(|_| rt::lean_internal_panic(\"Nat.repr produced an invalid numeral\"))");
    w.close("}");
    w.open("fn int_from_big(v: &::lungo::__num_bigint::BigInt) -> Obj {");
    w.line("ready();");
    w.line("let s = ::std::ffi::CString::new(v.to_string()).expect(\"decimal digits\");");
    w.line("unsafe { lean_cstr_to_int(s.as_ptr()) }");
    w.close("}");
    w.open("unsafe fn int_to_big(o: Obj) -> ::lungo::__num_bigint::BigInt {");
    w.line(format!("let s = unsafe {{ read_string({}) }};", call("int_repr", "Int.repr", "o")));
    w.line("s.parse().unwrap_or_else(|_| rt::lean_internal_panic(\"Int.repr produced an invalid numeral\"))");
    w.close("}");
    w.line("unsafe fn alloc_array(size: usize, capacity: usize) -> Obj { ready(); unsafe { lng_oracle_alloc_array(size, capacity) } }");
    w.line("unsafe fn alloc_sarray(elem_size: u32, size: usize, capacity: usize) -> Obj { ready(); unsafe { lng_oracle_alloc_sarray(elem_size, size, capacity) } }");
    w.line("unsafe fn alloc_closure(fun: *const (), arity: u32, num_fixed: u32) -> Obj { ready(); unsafe { lng_oracle_alloc_closure(fun, arity, num_fixed) } }");
    w.open("unsafe fn apply(f: Obj, args: &[Obj]) -> Obj {");
    w.line("let mut args = args.to_vec();");
    w.line("unsafe { lean_apply_n(f, args.len() as u32, args.as_mut_ptr()) }");
    w.close("}");
    w.line("unsafe fn alloc_external(data: *mut (), finalize: unsafe extern \"C\" fn(*mut ())) -> Obj { ready(); unsafe { lng_oracle_alloc_external(data, finalize) } }");
    w.line("unsafe fn external_data(o: Obj) -> *mut () { unsafe { lng_oracle_external_data(o) } }");
    w.open("unsafe fn io_error_to_string(err: Obj) -> ::std::string::String {");
    w.line(format!("unsafe {{ read_string({}) }}", call("io_error_to_string", "IO.Error.toString", "err")));
    w.close("}");
    w.open("unsafe fn mk_io_user_error(msg: Obj) -> Obj {");
    if owned_arg["IO.userError"] {
        w.line("unsafe { io_user_error(msg) }");
    } else {
        w.line("unsafe { let e = io_user_error(msg); lng_oracle_dec(msg); e }");
    }
    w.close("}");
    w.close("}");
    if let Some(entry) = &input.success.entry_point {
        let main = declaration(input, &entry.declaration)?;
        let with_args = main.params.iter().any(|p| p.ty != IrType::Void);
        w.line("");
        w.line("/// Runs the natively compiled Lean `main` and returns its exit code.");
        w.open("pub fn run_main(args: ::std::vec::Vec<::std::string::String>) -> i32 {");
        w.line("super::__lng::__initialize();");
        w.open("let run = move || -> i32 { unsafe {");
        if with_args {
            w.line("let mut list = rt::lean_box(0);");
            w.open("for a in args.iter().rev() {");
            w.line("let cell = lng_oracle_alloc_ctor(1, 2, 0);");
            w.line("rt::lean_ctor_set(cell, 0, <Backend as ::lungo::Backend>::mk_string(a));");
            w.line("rt::lean_ctor_set(cell, 1, list);");
            w.line("list = cell;");
            w.close("}");
            w.line(format!("let res = super::__lng::{}(list);", mangle(&main.name)));
        } else {
            w.line("let _ = &args;");
            w.line(format!("let res = super::__lng::{}();", mangle(&main.name)));
        }
        w.open("let code = if rt::lean_ptr_tag(res) == 0 {");
        if entry.returns_exit_code {
            w.line("rt::lean_unbox_uint32(rt::lean_ctor_get(res, 0)) as i32");
        } else {
            w.line("0");
        }
        w.dedent();
        w.open("} else {");
        w.line("let msg = <Backend as ::lungo::Backend>::io_error_to_string(rt::lean_ctor_get(res, 0));");
        w.line("::std::eprintln!(\"uncaught exception: {msg}\");");
        w.line("1");
        w.close("};");
        w.line("lng_oracle_dec(res);");
        w.line("code");
        w.close("} };");
        w.open("let code = ::std::thread::Builder::new()");
        w.line(".stack_size(rt::task::thread_stack_size())");
        w.line(".spawn(run)");
        w.line(".expect(\"cannot start the Lean main thread\")");
        w.line(".join()");
        w.line(".expect(\"the Lean main thread panicked\");");
        w.dedent();
        w.line("unsafe { lean_finalize_task_manager() };");
        w.line("code");
        w.close("}");
    }
    Ok(())
}
