#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = purge ]; then
    if command -v update-alternatives >/dev/null 2>&1; then
        update-alternatives --remove @{package} @{prefix}/@{package} || rm -f @{link}
    else
        rm -f @{link}
    fi
fi
