#!/bin/sh
set -e
if command -v update-alternatives >/dev/null 2>&1; then
    update-alternatives --install @{link} @{package} @{prefix}/@{package} 100 \
        || ln -sf @{prefix}/@{package} @{link}
else
    ln -sf @{prefix}/@{package} @{link}
fi
