//! The lungo runtime as a C library.
//!
//! Built as a static and a shared library (`liblungo`), it is the runtime that programs
//! generated by lungo's C backend link against, and that the Go, Python, Swift and TypeScript
//! bindings load. Its interface is `lungo.h` ([`lungo_runtime::header::HEADER`]). This crate only
//! links the runtime with its C ABI enabled; a release builds and packages it (`lungo-dist release-runtime`).

pub use lungo_runtime;
