// Generated by lungo 0.39.1865 from Lean 4.34.1 (Bridge IR 3). Do not edit.

#[doc(hidden)]
#[allow(non_snake_case, non_upper_case_globals, unused_mut, unused_variables, unused_assignments, unused_labels, unused_unsafe, unused_imports, unreachable_code, unreachable_patterns, dead_code, unsafe_op_in_unsafe_fn, clippy::all)]
pub mod __lng {
    use ::lungo::__runtime as rt;
    use rt::Obj;
    const _: () = rt::assert_abi::<1>();

    include!("modules/Formal-Session.rs");
    include!("modules/Init-Data-ByteArray-Basic.rs");
    include!("modules/Init-Data-ByteArray-Extra.rs");
    include!("modules/Init-Data-Int-Basic.rs");
    include!("modules/Init-Data-Int-Repr.rs");
    include!("modules/Init-Data-List-Basic.rs");
    include!("modules/Init-Data-Random.rs");
    include!("modules/Init-Data-Repr.rs");
    include!("modules/Init-Data-String-Basic.rs");
    include!("modules/Init-Data-String-Bootstrap.rs");
    include!("modules/Init-Data-String-Defs.rs");
    include!("modules/Init-Data-String-Modify.rs");
    include!("modules/Init-Data-UInt-Basic.rs");
    include!("modules/Init-Data-UInt-BasicAux.rs");
    include!("modules/Init-Prelude.rs");
    include!("modules/Init-System-IO.rs");
    include!("modules/Init-System-IOError.rs");
    include!("modules/Init-System-ST.rs");
    include!("modules/Init-Util.rs");

    // The runtime calls IO.Error.toString as `lean_io_error_to_string`.
    unsafe extern "C" fn e_l_IO_dError_dtoString(a_0: Obj) -> Obj {
        let r = l_IO_dError_dtoString(a_0);
        r
    }

    // The runtime calls IO.FS.Stream.ofHandle as `lean_stream_of_handle`.
    unsafe extern "C" fn e_l_IO_dFS_dStream_dofHandle(a_0: Obj) -> Obj {
        let r = l_IO_dFS_dStream_dofHandle(a_0);
        r
    }

    // The runtime calls _private.Init.System.IO.0.IO.eprintlnAux as `lean_io_eprintln`.
    unsafe extern "C" fn e_l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux(a_0: Obj) -> Obj {
        let r = l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux(a_0);
        r
    }

    // The runtime calls IO.userError as `lean_mk_io_user_error`.
    unsafe extern "C" fn e_l_IO_duserError(a_0: Obj) -> Obj {
        let r = l_IO_duserError(a_0);
        r
    }

    // The runtime calls IO.Error.mkEofError as `lean_mk_io_error_eof`.
    unsafe extern "C" fn e_l_IO_dError_dmkEofError(a_0: Obj) -> Obj {
        let r = l_IO_dError_dmkEofError(a_0);
        r
    }

    // The runtime calls IO.Error.mkAlreadyExists as `lean_mk_io_error_already_exists`.
    unsafe extern "C" fn e_l_IO_dError_dmkAlreadyExists(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkAlreadyExists(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkAlreadyExistsFile as `lean_mk_io_error_already_exists_file`.
    unsafe extern "C" fn e_l_IO_dError_dmkAlreadyExistsFile(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkAlreadyExistsFile(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkHardwareFault as `lean_mk_io_error_hardware_fault`.
    unsafe extern "C" fn e_l_IO_dError_dmkHardwareFault(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkHardwareFault(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkIllegalOperation as `lean_mk_io_error_illegal_operation`.
    unsafe extern "C" fn e_l_IO_dError_dmkIllegalOperation(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkIllegalOperation(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkInappropriateType as `lean_mk_io_error_inappropriate_type`.
    unsafe extern "C" fn e_l_IO_dError_dmkInappropriateType(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkInappropriateType(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkInappropriateTypeFile as `lean_mk_io_error_inappropriate_type_file`.
    unsafe extern "C" fn e_l_IO_dError_dmkInappropriateTypeFile(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkInappropriateTypeFile(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkInterrupted as `lean_mk_io_error_interrupted`.
    unsafe extern "C" fn e_l_IO_dError_dmkInterrupted(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkInterrupted(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkInvalidArgument as `lean_mk_io_error_invalid_argument`.
    unsafe extern "C" fn e_l_IO_dError_dmkInvalidArgument(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkInvalidArgument(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkInvalidArgumentFile as `lean_mk_io_error_invalid_argument_file`.
    unsafe extern "C" fn e_l_IO_dError_dmkInvalidArgumentFile(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkInvalidArgumentFile(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkNoFileOrDirectory as `lean_mk_io_error_no_file_or_directory`.
    unsafe extern "C" fn e_l_IO_dError_dmkNoFileOrDirectory(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkNoFileOrDirectory(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkNoSuchThing as `lean_mk_io_error_no_such_thing`.
    unsafe extern "C" fn e_l_IO_dError_dmkNoSuchThing(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkNoSuchThing(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkNoSuchThingFile as `lean_mk_io_error_no_such_thing_file`.
    unsafe extern "C" fn e_l_IO_dError_dmkNoSuchThingFile(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkNoSuchThingFile(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkOtherError as `lean_mk_io_error_other_error`.
    unsafe extern "C" fn e_l_IO_dError_dmkOtherError(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkOtherError(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkPermissionDenied as `lean_mk_io_error_permission_denied`.
    unsafe extern "C" fn e_l_IO_dError_dmkPermissionDenied(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkPermissionDenied(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkPermissionDeniedFile as `lean_mk_io_error_permission_denied_file`.
    unsafe extern "C" fn e_l_IO_dError_dmkPermissionDeniedFile(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkPermissionDeniedFile(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkProtocolError as `lean_mk_io_error_protocol_error`.
    unsafe extern "C" fn e_l_IO_dError_dmkProtocolError(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkProtocolError(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkResourceBusy as `lean_mk_io_error_resource_busy`.
    unsafe extern "C" fn e_l_IO_dError_dmkResourceBusy(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkResourceBusy(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkResourceExhausted as `lean_mk_io_error_resource_exhausted`.
    unsafe extern "C" fn e_l_IO_dError_dmkResourceExhausted(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkResourceExhausted(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkResourceExhaustedFile as `lean_mk_io_error_resource_exhausted_file`.
    unsafe extern "C" fn e_l_IO_dError_dmkResourceExhaustedFile(a_0: Obj, a_1: u32, a_2: Obj) -> Obj {
        let r = l_IO_dError_dmkResourceExhaustedFile(a_0, a_1, a_2);
        r
    }

    // The runtime calls IO.Error.mkResourceVanished as `lean_mk_io_error_resource_vanished`.
    unsafe extern "C" fn e_l_IO_dError_dmkResourceVanished(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkResourceVanished(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkTimeExpired as `lean_mk_io_error_time_expired`.
    unsafe extern "C" fn e_l_IO_dError_dmkTimeExpired(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkTimeExpired(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkUnsatisfiedConstraints as `lean_mk_io_error_unsatisfied_constraints`.
    unsafe extern "C" fn e_l_IO_dError_dmkUnsatisfiedConstraints(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkUnsatisfiedConstraints(a_0, a_1);
        r
    }

    // The runtime calls IO.Error.mkUnsupportedOperation as `lean_mk_io_error_unsupported_operation`.
    unsafe extern "C" fn e_l_IO_dError_dmkUnsupportedOperation(a_0: u32, a_1: Obj) -> Obj {
        let r = l_IO_dError_dmkUnsupportedOperation(a_0, a_1);
        r
    }

    /// Initializes the Lean program: runs every module initializer once, in import order.
    pub fn __initialize() {
        static INIT: ::std::sync::Once = ::std::sync::Once::new();
        INIT.call_once(|| unsafe {
            rt::exports::register("lean_io_error_to_string", e_l_IO_dError_dtoString as *const ());
            rt::exports::register("lean_stream_of_handle", e_l_IO_dFS_dStream_dofHandle as *const ());
            rt::exports::register("lean_io_eprintln", e_l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux as *const ());
            rt::exports::register("lean_mk_io_user_error", e_l_IO_duserError as *const ());
            rt::exports::register("lean_mk_io_error_eof", e_l_IO_dError_dmkEofError as *const ());
            rt::exports::register("lean_mk_io_error_already_exists", e_l_IO_dError_dmkAlreadyExists as *const ());
            rt::exports::register("lean_mk_io_error_already_exists_file", e_l_IO_dError_dmkAlreadyExistsFile as *const ());
            rt::exports::register("lean_mk_io_error_hardware_fault", e_l_IO_dError_dmkHardwareFault as *const ());
            rt::exports::register("lean_mk_io_error_illegal_operation", e_l_IO_dError_dmkIllegalOperation as *const ());
            rt::exports::register("lean_mk_io_error_inappropriate_type", e_l_IO_dError_dmkInappropriateType as *const ());
            rt::exports::register("lean_mk_io_error_inappropriate_type_file", e_l_IO_dError_dmkInappropriateTypeFile as *const ());
            rt::exports::register("lean_mk_io_error_interrupted", e_l_IO_dError_dmkInterrupted as *const ());
            rt::exports::register("lean_mk_io_error_invalid_argument", e_l_IO_dError_dmkInvalidArgument as *const ());
            rt::exports::register("lean_mk_io_error_invalid_argument_file", e_l_IO_dError_dmkInvalidArgumentFile as *const ());
            rt::exports::register("lean_mk_io_error_no_file_or_directory", e_l_IO_dError_dmkNoFileOrDirectory as *const ());
            rt::exports::register("lean_mk_io_error_no_such_thing", e_l_IO_dError_dmkNoSuchThing as *const ());
            rt::exports::register("lean_mk_io_error_no_such_thing_file", e_l_IO_dError_dmkNoSuchThingFile as *const ());
            rt::exports::register("lean_mk_io_error_other_error", e_l_IO_dError_dmkOtherError as *const ());
            rt::exports::register("lean_mk_io_error_permission_denied", e_l_IO_dError_dmkPermissionDenied as *const ());
            rt::exports::register("lean_mk_io_error_permission_denied_file", e_l_IO_dError_dmkPermissionDeniedFile as *const ());
            rt::exports::register("lean_mk_io_error_protocol_error", e_l_IO_dError_dmkProtocolError as *const ());
            rt::exports::register("lean_mk_io_error_resource_busy", e_l_IO_dError_dmkResourceBusy as *const ());
            rt::exports::register("lean_mk_io_error_resource_exhausted", e_l_IO_dError_dmkResourceExhausted as *const ());
            rt::exports::register("lean_mk_io_error_resource_exhausted_file", e_l_IO_dError_dmkResourceExhaustedFile as *const ());
            rt::exports::register("lean_mk_io_error_resource_vanished", e_l_IO_dError_dmkResourceVanished as *const ());
            rt::exports::register("lean_mk_io_error_time_expired", e_l_IO_dError_dmkTimeExpired as *const ());
            rt::exports::register("lean_mk_io_error_unsatisfied_constraints", e_l_IO_dError_dmkUnsatisfiedConstraints as *const ());
            rt::exports::register("lean_mk_io_error_unsupported_operation", e_l_IO_dError_dmkUnsupportedOperation as *const ());
            // Init.Data.Random
            { let v = rt::check_initializer("IO.stdGenRef", l___private_dInit_dData_dRandom_d0_dinitFn_d___x40__dInit_dData_dRandom_d2456098205_d__hygCtx_d__hyg_d2()); I_l_IO_dstdGenRef.set_obj(v); }
            rt::end_initialization();
        });
    }
}

/// Lean: `Formal.Op`
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum Op {
    Open,
    Close,
    Tick,
}

#[allow(unused_imports, unused_unsafe)]
unsafe impl ::lungo::LeanType<::lungo::RustBackend> for Op {
    fn into_lean(self) -> ::lungo::__runtime::Obj {
        use ::lungo::__runtime as rt;
        unsafe {
            match self {
                Op::Open => rt::lean_box(0),
                Op::Close => rt::lean_box(1),
                Op::Tick => rt::lean_box(2),
            }
        }
    }
    unsafe fn from_lean(o: ::lungo::__runtime::Obj) -> Self {
        use ::lungo::__runtime as rt;
        unsafe {
            match rt::lean_obj_tag(o) {
                0 => Op::Open,
                1 => Op::Close,
                2 => Op::Tick,
                tag => rt::lean_internal_panic(&::std::format!("invalid constructor tag {tag} for Formal.Op")),
            }
        }
    }
}

/// Lean: `Formal.Sess`
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Sess {
    pub is_open: bool,
    pub count: ::lungo::Nat,
}

#[allow(unused_imports, unused_unsafe)]
unsafe impl ::lungo::LeanType<::lungo::RustBackend> for Sess {
    fn into_lean(self) -> ::lungo::__runtime::Obj {
        use ::lungo::__runtime as rt;
        unsafe {
            let Sess { is_open: f0, count: f1 } = self;
            let o = ::lungo::__facade::alloc_ctor::<::lungo::RustBackend>(0, 1, 1);
            rt::lean_ctor_set_uint8(o, ::core::mem::size_of::<usize>(), ::lungo::__facade::to_small::<::lungo::RustBackend, _>(f0) as u8);
            rt::lean_ctor_set(o, 0, ::lungo::LeanType::<::lungo::RustBackend>::into_lean(f1));
            o
        }
    }
    unsafe fn from_lean(o: ::lungo::__runtime::Obj) -> Self {
        use ::lungo::__runtime as rt;
        unsafe {
            match rt::lean_obj_tag(o) {
                0 => Sess { is_open: ::lungo::__facade::from_small::<::lungo::RustBackend, bool>(rt::lean_ctor_get_uint8(o, ::core::mem::size_of::<usize>()) as usize), count: <::lungo::Nat as ::lungo::LeanType<::lungo::RustBackend>>::from_lean(rt::lean_ctor_get(o, 0)) },
                tag => rt::lean_internal_panic(&::std::format!("invalid constructor tag {tag} for Formal.Sess")),
            }
        }
    }
}

/// Lean: `Formal.apply : Formal.Op → Formal.Sess → Option Formal.Sess`
/// 
/// Source: lean/Formal/Session.lean:14:1
#[allow(unused_imports, unused_unsafe, clippy::all)]
pub fn apply(a: Op, a_1: Sess) -> ::core::option::Option<Sess> {
    use ::lungo::__runtime::{self as rt, Obj};
    __lng::__initialize();
    unsafe {
        let __p0: u8 = ::lungo::__facade::to_small::<::lungo::RustBackend, _>(a) as u8;
        let __p1: Obj = ::lungo::LeanType::<::lungo::RustBackend>::into_lean(a_1);
        let __r: Obj = __lng::l_Formal_dapply(__p0, __p1);
        ::lungo::__facade::take::<::lungo::RustBackend, ::core::option::Option<Sess>>(__r)
    }
}

/// Lean: `Formal.run : List Formal.Op → Formal.Sess → Option Formal.Sess`
/// 
/// Source: lean/Formal/Session.lean:38:1
#[allow(unused_imports, unused_unsafe, clippy::all)]
pub fn run(a: ::lungo::List<Op>, a_1: Sess) -> ::core::option::Option<Sess> {
    use ::lungo::__runtime::{self as rt, Obj};
    __lng::__initialize();
    unsafe {
        let __p0: Obj = ::lungo::LeanType::<::lungo::RustBackend>::into_lean(a);
        let __p1: Obj = ::lungo::LeanType::<::lungo::RustBackend>::into_lean(a_1);
        let __r: Obj = __lng::l_Formal_drun(__p0, __p1);
        ::lungo::__facade::dec::<::lungo::RustBackend>(__p0);
        ::lungo::__facade::take::<::lungo::RustBackend, ::core::option::Option<Sess>>(__r)
    }
}

pub mod op {
    /// Lean: `Formal.Op.ofNat : Nat → Formal.Op`
    /// 
    /// Source: lean/Formal/Session.lean
    #[allow(unused_imports, unused_unsafe, clippy::all)]
    pub fn of_nat(x: ::lungo::Nat) -> super::Op {
        use ::lungo::__runtime::{self as rt, Obj};
        super::__lng::__initialize();
        unsafe {
            let __p0: Obj = ::lungo::LeanType::<::lungo::RustBackend>::into_lean(x);
            let __r: u8 = super::__lng::l_Formal_dOp_dofNat(__p0);
            ::lungo::__facade::dec::<::lungo::RustBackend>(__p0);
            ::lungo::__facade::from_small::<::lungo::RustBackend, super::Op>(__r as usize)
        }
    }

}

#[doc(hidden)]
pub mod __opaque {
    //! Marker types identifying Lean types exposed as opaque values.
}

/// Static metadata about the generated declarations.
pub mod __meta {
    /// The Lean release the code was compiled with.
    pub const LEAN_VERSION: &str = "4.34.1";
    pub const LEAN_GITHASH: &str = "5045d0056413266e57c625dcd7c365b10e377c52";
    pub const BIR_VERSION: u32 = 3;
    pub const GENERATOR_VERSION: &str = "0.39.1865";

    static DECLARATIONS: &[::lungo::DeclarationInfo] = &[
        ::lungo::DeclarationInfo {
            lean_name: "Formal.Op.ofNat",
            module: "Formal.Session",
            source_file: Some("lean/Formal/Session.lean"),
            range: None,
            lean_type: "Nat → Formal.Op",
            compiled_signature: "(@& tobj) -> u8",
            rust_path: "op::of_nat",
            trust: ::lungo::ExportTrust {
                axioms: &[],
                depends_on_sorry: false,
                unsafe_dependencies: &[],
                partial_dependencies: &[],
                extern_dependencies: &["lean_nat_dec_le"],
            },
        },
        ::lungo::DeclarationInfo {
            lean_name: "Formal.apply",
            module: "Formal.Session",
            source_file: Some("lean/Formal/Session.lean"),
            range: Some(::lungo::SourceRange { start: ::lungo::SourcePosition { line: 14, column: 1 }, end: ::lungo::SourcePosition { line: 26, column: 43 } }),
            lean_type: "Formal.Op → Formal.Sess → Option Formal.Sess",
            compiled_signature: "(u8, obj) -> tobj",
            rust_path: "apply",
            trust: ::lungo::ExportTrust {
                axioms: &[],
                depends_on_sorry: false,
                unsafe_dependencies: &[],
                partial_dependencies: &[],
                extern_dependencies: &["lean_nat_add"],
            },
        },
        ::lungo::DeclarationInfo {
            lean_name: "Formal.run",
            module: "Formal.Session",
            source_file: Some("lean/Formal/Session.lean"),
            range: Some(::lungo::SourceRange { start: ::lungo::SourcePosition { line: 38, column: 1 }, end: ::lungo::SourcePosition { line: 41, column: 48 } }),
            lean_type: "List Formal.Op → Formal.Sess → Option Formal.Sess",
            compiled_signature: "(@& tobj, obj) -> tobj",
            rust_path: "run",
            trust: ::lungo::ExportTrust {
                axioms: &[],
                depends_on_sorry: false,
                unsafe_dependencies: &[],
                partial_dependencies: &[],
                extern_dependencies: &["lean_nat_add"],
            },
        },
    ];

    /// Metadata of the exported Lean declaration with fully qualified name `lean_name`.
    pub fn declaration(lean_name: &str) -> ::core::option::Option<&'static ::lungo::DeclarationInfo> {
        DECLARATIONS.binary_search_by(|d| d.lean_name.cmp(lean_name)).ok().map(|i| &DECLARATIONS[i])
    }

    /// Metadata of every exported declaration, sorted by Lean name.
    pub fn declarations() -> &'static [::lungo::DeclarationInfo] {
        DECLARATIONS
    }
}
