// Compiled Lean module Formal.Session. Generated by lungo; do not edit.

// Lean: Formal.Op.close.elim
// Source: lean/Formal/Session.lean:5:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dclose_delim(x_1: Obj, x_2: u8, x_3: Obj, x_4: Obj) -> Obj {
    rt::lean_inc(x_4);
    return x_4;
}

// Lean: Formal.Op.close.elim._boxed
// Compiled from: Formal.Op.close.elim
// Source: lean/Formal/Session.lean:5:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dclose_delim_d__boxed(x_1: Obj, x_2: Obj, x_3: Obj, x_4: Obj) -> Obj {
    let x_5: u8 = rt::lean_unbox(x_2) as u8;
    let x_6: Obj = l_Formal_dOp_dclose_delim(x_1, x_5, x_3, x_4);
    rt::lean_dec(x_4);
    return x_6;
}

// Lean: Formal.Op.close.elim._redArg
// Compiled from: Formal.Op.close.elim
// Source: lean/Formal/Session.lean:5:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dclose_delim_d__redArg(x_1: Obj) -> Obj {
    rt::lean_inc(x_1);
    return x_1;
}

// Lean: Formal.Op.close.elim._redArg._boxed
// Compiled from: Formal.Op.close.elim
// Source: lean/Formal/Session.lean:5:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dclose_delim_d__redArg_d__boxed(x_1: Obj) -> Obj {
    let x_2: Obj = l_Formal_dOp_dclose_delim_d__redArg(x_1);
    rt::lean_dec(x_1);
    return x_2;
}

// Lean: Formal.Op.ctorElim
// Source: lean/Formal/Session.lean:3:1
pub(crate) unsafe extern "C" fn l_Formal_dOp_dctorElim(x_1: Obj, x_2: Obj, x_3: u8, x_4: Obj, x_5: Obj) -> Obj {
    rt::lean_inc(x_5);
    return x_5;
}

// Lean: Formal.Op.ctorElim._boxed
// Compiled from: Formal.Op.ctorElim
// Source: lean/Formal/Session.lean:3:1
pub(crate) unsafe extern "C" fn l_Formal_dOp_dctorElim_d__boxed(x_1: Obj, x_2: Obj, x_3: Obj, x_4: Obj, x_5: Obj) -> Obj {
    let x_6: u8 = rt::lean_unbox(x_3) as u8;
    let x_7: Obj = l_Formal_dOp_dctorElim(x_1, x_2, x_6, x_4, x_5);
    rt::lean_dec(x_5);
    rt::lean_dec(x_2);
    return x_7;
}

// Lean: Formal.Op.ctorElim._redArg
// Compiled from: Formal.Op.ctorElim
// Source: lean/Formal/Session.lean:3:1
pub(crate) unsafe extern "C" fn l_Formal_dOp_dctorElim_d__redArg(x_1: Obj) -> Obj {
    rt::lean_inc(x_1);
    return x_1;
}

// Lean: Formal.Op.ctorElim._redArg._boxed
// Compiled from: Formal.Op.ctorElim
// Source: lean/Formal/Session.lean:3:1
pub(crate) unsafe extern "C" fn l_Formal_dOp_dctorElim_d__redArg_d__boxed(x_1: Obj) -> Obj {
    let x_2: Obj = l_Formal_dOp_dctorElim_d__redArg(x_1);
    rt::lean_dec(x_1);
    return x_2;
}

// Lean: Formal.Op.ctorIdx
// Source: lean/Formal/Session.lean
pub(crate) unsafe extern "C" fn l_Formal_dOp_dctorIdx(x_1: u8) -> Obj {
    match x_1 {
        0 => {
            let x_2: Obj = rt::nat::lean_usize_to_nat(0);
            return x_2;
        }
        1 => {
            let x_3: Obj = rt::nat::lean_usize_to_nat(1);
            return x_3;
        }
        _ => {
            let x_4: Obj = rt::nat::lean_usize_to_nat(2);
            return x_4;
        }
    }
}

// Lean: Formal.Op.ctorIdx._boxed
// Compiled from: Formal.Op.ctorIdx
// Source: lean/Formal/Session.lean
pub(crate) unsafe extern "C" fn l_Formal_dOp_dctorIdx_d__boxed(x_1: Obj) -> Obj {
    let x_2: u8 = rt::lean_unbox(x_1) as u8;
    let x_3: Obj = l_Formal_dOp_dctorIdx(x_2);
    return x_3;
}

// Lean: Formal.Op.ofNat
// Source: lean/Formal/Session.lean
pub(crate) unsafe extern "C" fn l_Formal_dOp_dofNat(x_1: Obj) -> u8 {
    let x_2: Obj = rt::nat::lean_usize_to_nat(0);
    let x_3: u8 = l_Nat_dble(x_1, x_2);
    match x_3 {
        0 => {
            let x_4: Obj = rt::nat::lean_usize_to_nat(1);
            let x_5: u8 = l_Nat_dble(x_1, x_4);
            match x_5 {
                0 => {
                    let x_6: u8 = 2u8;
                    return x_6;
                }
                _ => {
                    let x_7: u8 = 1u8;
                    return x_7;
                }
            }
        }
        _ => {
            let x_8: u8 = 0u8;
            return x_8;
        }
    }
}

// Lean: Formal.Op.ofNat._boxed
// Compiled from: Formal.Op.ofNat
// Source: lean/Formal/Session.lean
pub(crate) unsafe extern "C" fn l_Formal_dOp_dofNat_d__boxed(x_1: Obj) -> Obj {
    let x_2: u8 = l_Formal_dOp_dofNat(x_1);
    rt::lean_dec(x_1);
    let x_3: Obj = rt::lean_box(x_2 as usize);
    return x_3;
}

// Lean: Formal.Op.open.elim
// Source: lean/Formal/Session.lean:4:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dopen_delim(x_1: Obj, x_2: u8, x_3: Obj, x_4: Obj) -> Obj {
    rt::lean_inc(x_4);
    return x_4;
}

// Lean: Formal.Op.open.elim._boxed
// Compiled from: Formal.Op.open.elim
// Source: lean/Formal/Session.lean:4:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dopen_delim_d__boxed(x_1: Obj, x_2: Obj, x_3: Obj, x_4: Obj) -> Obj {
    let x_5: u8 = rt::lean_unbox(x_2) as u8;
    let x_6: Obj = l_Formal_dOp_dopen_delim(x_1, x_5, x_3, x_4);
    rt::lean_dec(x_4);
    return x_6;
}

// Lean: Formal.Op.open.elim._redArg
// Compiled from: Formal.Op.open.elim
// Source: lean/Formal/Session.lean:4:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dopen_delim_d__redArg(x_1: Obj) -> Obj {
    rt::lean_inc(x_1);
    return x_1;
}

// Lean: Formal.Op.open.elim._redArg._boxed
// Compiled from: Formal.Op.open.elim
// Source: lean/Formal/Session.lean:4:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dopen_delim_d__redArg_d__boxed(x_1: Obj) -> Obj {
    let x_2: Obj = l_Formal_dOp_dopen_delim_d__redArg(x_1);
    rt::lean_dec(x_1);
    return x_2;
}

// Lean: Formal.Op.tick.elim
// Source: lean/Formal/Session.lean:6:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dtick_delim(x_1: Obj, x_2: u8, x_3: Obj, x_4: Obj) -> Obj {
    rt::lean_inc(x_4);
    return x_4;
}

// Lean: Formal.Op.tick.elim._boxed
// Compiled from: Formal.Op.tick.elim
// Source: lean/Formal/Session.lean:6:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dtick_delim_d__boxed(x_1: Obj, x_2: Obj, x_3: Obj, x_4: Obj) -> Obj {
    let x_5: u8 = rt::lean_unbox(x_2) as u8;
    let x_6: Obj = l_Formal_dOp_dtick_delim(x_1, x_5, x_3, x_4);
    rt::lean_dec(x_4);
    return x_6;
}

// Lean: Formal.Op.tick.elim._redArg
// Compiled from: Formal.Op.tick.elim
// Source: lean/Formal/Session.lean:6:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dtick_delim_d__redArg(x_1: Obj) -> Obj {
    rt::lean_inc(x_1);
    return x_1;
}

// Lean: Formal.Op.tick.elim._redArg._boxed
// Compiled from: Formal.Op.tick.elim
// Source: lean/Formal/Session.lean:6:3
pub(crate) unsafe extern "C" fn l_Formal_dOp_dtick_delim_d__redArg_d__boxed(x_1: Obj) -> Obj {
    let x_2: Obj = l_Formal_dOp_dtick_delim_d__redArg(x_1);
    rt::lean_dec(x_1);
    return x_2;
}

// Lean: Formal.apply
// Source: lean/Formal/Session.lean:14:1
pub(crate) unsafe extern "C" fn l_Formal_dapply(x_1: u8, x_2: Obj) -> Obj {
    match x_1 {
        0 => {
            let x_3: u8 = rt::lean_ctor_get_uint8(x_2, ::core::mem::size_of::<usize>());
            match x_3 {
                0 => {
                    let x_4: Obj = rt::lean_ctor_get(x_2, 0);
                    let mut x_6: Obj;
                    let mut x_7: u8;
                    'b5: {
                        let x_13: u8 = (!rt::lean_is_exclusive(x_2)) as u8;
                        match x_13 {
                            0 => {
                                x_6 = x_2;
                                x_7 = x_13;
                                break 'b5;
                            }
                            _ => {
                                rt::lean_inc(x_4);
                                rt::lean_dec(x_2);
                                x_6 = rt::lean_box(0);
                                x_7 = x_13;
                                break 'b5;
                            }
                        }
                    }
                    let x_8: u8 = 1u8;
                    let mut x_10: Obj;
                    'b9: {
                        match x_7 {
                            0 => {
                                x_10 = x_6;
                                break 'b9;
                            }
                            _ => {
                                let x_12: Obj = rt::lean_alloc_ctor(0, 1, 1);
                                rt::lean_ctor_set(x_12, 0, x_4);
                                x_10 = x_12;
                                break 'b9;
                            }
                        }
                    }
                    rt::lean_ctor_set_uint8(x_10, ::core::mem::size_of::<usize>(), x_8);
                    let x_11: Obj = rt::lean_alloc_ctor(1, 1, 0);
                    rt::lean_ctor_set(x_11, 0, x_10);
                    return x_11;
                }
                _ => {
                    rt::lean_dec_ref(x_2);
                    let x_14: Obj = rt::lean_box(0);
                    return x_14;
                }
            }
        }
        1 => {
            let x_15: u8 = rt::lean_ctor_get_uint8(x_2, ::core::mem::size_of::<usize>());
            match x_15 {
                0 => {
                    rt::lean_dec_ref(x_2);
                    let x_16: Obj = rt::lean_box(0);
                    return x_16;
                }
                _ => {
                    let x_17: Obj = rt::lean_ctor_get(x_2, 0);
                    let mut x_19: Obj;
                    let mut x_20: u8;
                    'b18: {
                        let x_26: u8 = (!rt::lean_is_exclusive(x_2)) as u8;
                        match x_26 {
                            0 => {
                                x_19 = x_2;
                                x_20 = x_26;
                                break 'b18;
                            }
                            _ => {
                                rt::lean_inc(x_17);
                                rt::lean_dec(x_2);
                                x_19 = rt::lean_box(0);
                                x_20 = x_26;
                                break 'b18;
                            }
                        }
                    }
                    let x_21: u8 = 0u8;
                    let mut x_23: Obj;
                    'b22: {
                        match x_20 {
                            0 => {
                                x_23 = x_19;
                                break 'b22;
                            }
                            _ => {
                                let x_25: Obj = rt::lean_alloc_ctor(0, 1, 1);
                                rt::lean_ctor_set(x_25, 0, x_17);
                                x_23 = x_25;
                                break 'b22;
                            }
                        }
                    }
                    rt::lean_ctor_set_uint8(x_23, ::core::mem::size_of::<usize>(), x_21);
                    let x_24: Obj = rt::lean_alloc_ctor(1, 1, 0);
                    rt::lean_ctor_set(x_24, 0, x_23);
                    return x_24;
                }
            }
        }
        _ => {
            let x_27: u8 = rt::lean_ctor_get_uint8(x_2, ::core::mem::size_of::<usize>());
            let x_28: Obj = rt::lean_ctor_get(x_2, 0);
            let mut x_30: Obj;
            let mut x_31: u8;
            'b29: {
                let x_38: u8 = (!rt::lean_is_exclusive(x_2)) as u8;
                match x_38 {
                    0 => {
                        x_30 = x_2;
                        x_31 = x_38;
                        break 'b29;
                    }
                    _ => {
                        rt::lean_inc(x_28);
                        rt::lean_dec(x_2);
                        x_30 = rt::lean_box(0);
                        x_31 = x_38;
                        break 'b29;
                    }
                }
            }
            let x_32: Obj = rt::nat::lean_usize_to_nat(1);
            let x_33: Obj = l_Nat_dadd(x_28, x_32);
            rt::lean_dec(x_28);
            let mut x_35: Obj;
            'b34: {
                match x_31 {
                    0 => {
                        rt::lean_ctor_set(x_30, 0, x_33);
                        x_35 = x_30;
                        break 'b34;
                    }
                    _ => {
                        let x_37: Obj = rt::lean_alloc_ctor(0, 1, 1);
                        rt::lean_ctor_set(x_37, 0, x_33);
                        rt::lean_ctor_set_uint8(x_37, ::core::mem::size_of::<usize>(), x_27);
                        x_35 = x_37;
                        break 'b34;
                    }
                }
            }
            let x_36: Obj = rt::lean_alloc_ctor(1, 1, 0);
            rt::lean_ctor_set(x_36, 0, x_35);
            return x_36;
        }
    }
}

// Lean: Formal.apply._boxed
// Compiled from: Formal.apply
// Source: lean/Formal/Session.lean:14:1
pub(crate) unsafe extern "C" fn l_Formal_dapply_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: u8 = rt::lean_unbox(x_1) as u8;
    let x_4: Obj = l_Formal_dapply(x_3, x_2);
    return x_4;
}

// Lean: Formal.instDecidableEqOp
// Source: lean/Formal/Session.lean:7:18
pub(crate) unsafe extern "C" fn l_Formal_dinstDecidableEqOp(x_1: u8, x_2: u8) -> u8 {
    let x_3: Obj = l_Formal_dOp_dctorIdx(x_1);
    let x_4: Obj = l_Formal_dOp_dctorIdx(x_2);
    let x_5: u8 = l_Nat_ddecEq(x_3, x_4);
    rt::lean_dec(x_4);
    rt::lean_dec(x_3);
    return x_5;
}

// Lean: Formal.instDecidableEqOp._boxed
// Compiled from: Formal.instDecidableEqOp
// Source: lean/Formal/Session.lean:7:18
pub(crate) unsafe extern "C" fn l_Formal_dinstDecidableEqOp_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: u8 = rt::lean_unbox(x_1) as u8;
    let x_4: u8 = rt::lean_unbox(x_2) as u8;
    let x_5: u8 = l_Formal_dinstDecidableEqOp(x_3, x_4);
    let x_6: Obj = rt::lean_box(x_5 as usize);
    return x_6;
}

// Lean: Formal.instDecidableEqSess
// Source: lean/Formal/Session.lean:12:18
pub(crate) unsafe extern "C" fn l_Formal_dinstDecidableEqSess(x_1: Obj, x_2: Obj) -> u8 {
    let x_3: u8 = l_Formal_dinstDecidableEqSess_ddecEq(x_1, x_2);
    return x_3;
}

// Lean: Formal.instDecidableEqSess._boxed
// Compiled from: Formal.instDecidableEqSess
// Source: lean/Formal/Session.lean:12:18
pub(crate) unsafe extern "C" fn l_Formal_dinstDecidableEqSess_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: u8 = l_Formal_dinstDecidableEqSess(x_1, x_2);
    rt::lean_dec_ref(x_2);
    rt::lean_dec_ref(x_1);
    let x_4: Obj = rt::lean_box(x_3 as usize);
    return x_4;
}

// Lean: Formal.instDecidableEqSess.decEq
// Source: lean/Formal/Session.lean:12:18
pub(crate) unsafe extern "C" fn l_Formal_dinstDecidableEqSess_ddecEq(x_1: Obj, x_2: Obj) -> u8 {
    let x_3: u8 = rt::lean_ctor_get_uint8(x_1, ::core::mem::size_of::<usize>());
    match x_3 {
        0 => {
            let x_4: u8 = rt::lean_ctor_get_uint8(x_2, ::core::mem::size_of::<usize>());
            match x_4 {
                0 => {
                    let x_5: Obj = rt::lean_ctor_get(x_1, 0);
                    let x_6: Obj = rt::lean_ctor_get(x_2, 0);
                    let x_7: u8 = l_Nat_ddecEq(x_5, x_6);
                    return x_7;
                }
                _ => {
                    return x_3;
                }
            }
        }
        _ => {
            let x_8: u8 = rt::lean_ctor_get_uint8(x_2, ::core::mem::size_of::<usize>());
            match x_8 {
                0 => {
                    return x_8;
                }
                _ => {
                    let x_9: Obj = rt::lean_ctor_get(x_1, 0);
                    let x_10: Obj = rt::lean_ctor_get(x_2, 0);
                    let x_11: u8 = l_Nat_ddecEq(x_9, x_10);
                    return x_11;
                }
            }
        }
    }
}

// Lean: Formal.instDecidableEqSess.decEq._boxed
// Compiled from: Formal.instDecidableEqSess.decEq
// Source: lean/Formal/Session.lean:12:18
pub(crate) unsafe extern "C" fn l_Formal_dinstDecidableEqSess_ddecEq_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: u8 = l_Formal_dinstDecidableEqSess_ddecEq(x_1, x_2);
    rt::lean_dec_ref(x_2);
    rt::lean_dec_ref(x_1);
    let x_4: Obj = rt::lean_box(x_3 as usize);
    return x_4;
}

// Lean: Formal.instReprOp
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprOp_d__closed__0();
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp() -> Obj {
    C_l_Formal_dinstReprOp.get(l_Formal_dinstReprOp__init)
}

// Lean: Formal.instReprOp._closed_0
// Compiled from: Formal.instReprOp
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_d__closed__0: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_d__closed__0__init() -> Obj {
    let x_1: Obj = rt::lean_alloc_closure(l_Formal_dinstReprOp_drepr_d__boxed as *const (), 2, 0);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_d__closed__0() -> Obj {
    C_l_Formal_dinstReprOp_d__closed__0.get(l_Formal_dinstReprOp_d__closed__0__init)
}

// Lean: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
pub(crate) unsafe extern "C" fn l_Formal_dinstReprOp_drepr(x_1: u8, x_2: Obj) -> Obj {
    let mut x_4: Obj;
    'b3: {
        let mut x_11: Obj;
        'b10: {
            let mut x_18: Obj;
            'b17: {
                match x_1 {
                    0 => {
                        let x_24: Obj = rt::nat::lean_usize_to_nat(1024);
                        let x_25: u8 = l_Nat_ddecLe(x_24, x_2);
                        match x_25 {
                            0 => {
                                let x_26: Obj = l_Formal_dinstReprOp_drepr_d__closed__6();
                                x_4 = x_26;
                                break 'b3;
                            }
                            _ => {
                                let x_27: Obj = l_Formal_dinstReprOp_drepr_d__closed__7();
                                x_4 = x_27;
                                break 'b3;
                            }
                        }
                    }
                    1 => {
                        let x_28: Obj = rt::nat::lean_usize_to_nat(1024);
                        let x_29: u8 = l_Nat_ddecLe(x_28, x_2);
                        match x_29 {
                            0 => {
                                let x_30: Obj = l_Formal_dinstReprOp_drepr_d__closed__6();
                                x_11 = x_30;
                                break 'b10;
                            }
                            _ => {
                                let x_31: Obj = l_Formal_dinstReprOp_drepr_d__closed__7();
                                x_11 = x_31;
                                break 'b10;
                            }
                        }
                    }
                    _ => {
                        let x_32: Obj = rt::nat::lean_usize_to_nat(1024);
                        let x_33: u8 = l_Nat_ddecLe(x_32, x_2);
                        match x_33 {
                            0 => {
                                let x_34: Obj = l_Formal_dinstReprOp_drepr_d__closed__6();
                                x_18 = x_34;
                                break 'b17;
                            }
                            _ => {
                                let x_35: Obj = l_Formal_dinstReprOp_drepr_d__closed__7();
                                x_18 = x_35;
                                break 'b17;
                            }
                        }
                    }
                }
            }
            let x_19: Obj = l_Formal_dinstReprOp_drepr_d__closed__5();
            rt::lean_inc(x_18);
            let x_20: Obj = rt::lean_alloc_ctor(4, 2, 0);
            rt::lean_ctor_set(x_20, 0, x_18);
            rt::lean_ctor_set(x_20, 1, x_19);
            let x_21: u8 = 0u8;
            let x_22: Obj = rt::lean_alloc_ctor(6, 1, 1);
            rt::lean_ctor_set(x_22, 0, x_20);
            rt::lean_ctor_set_uint8(x_22, ::core::mem::size_of::<usize>(), x_21);
            let x_23: Obj = l_Repr_daddAppParen(x_22, x_2);
            return x_23;
        }
        let x_12: Obj = l_Formal_dinstReprOp_drepr_d__closed__3();
        rt::lean_inc(x_11);
        let x_13: Obj = rt::lean_alloc_ctor(4, 2, 0);
        rt::lean_ctor_set(x_13, 0, x_11);
        rt::lean_ctor_set(x_13, 1, x_12);
        let x_14: u8 = 0u8;
        let x_15: Obj = rt::lean_alloc_ctor(6, 1, 1);
        rt::lean_ctor_set(x_15, 0, x_13);
        rt::lean_ctor_set_uint8(x_15, ::core::mem::size_of::<usize>(), x_14);
        let x_16: Obj = l_Repr_daddAppParen(x_15, x_2);
        return x_16;
    }
    let x_5: Obj = l_Formal_dinstReprOp_drepr_d__closed__1();
    rt::lean_inc(x_4);
    let x_6: Obj = rt::lean_alloc_ctor(4, 2, 0);
    rt::lean_ctor_set(x_6, 0, x_4);
    rt::lean_ctor_set(x_6, 1, x_5);
    let x_7: u8 = 0u8;
    let x_8: Obj = rt::lean_alloc_ctor(6, 1, 1);
    rt::lean_ctor_set(x_8, 0, x_6);
    rt::lean_ctor_set_uint8(x_8, ::core::mem::size_of::<usize>(), x_7);
    let x_9: Obj = l_Repr_daddAppParen(x_8, x_2);
    return x_9;
}

// Lean: Formal.instReprOp.repr._boxed
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
pub(crate) unsafe extern "C" fn l_Formal_dinstReprOp_drepr_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: u8 = rt::lean_unbox(x_1) as u8;
    let x_4: Obj = l_Formal_dinstReprOp_drepr(x_3, x_2);
    rt::lean_dec(x_2);
    return x_4;
}

// Lean: Formal.instReprOp.repr._closed_0
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__0: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__0__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b"Formal.Op.open", 14);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__0() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__0.get(l_Formal_dinstReprOp_drepr_d__closed__0__init)
}

// Lean: Formal.instReprOp.repr._closed_1
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__1: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__1__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprOp_drepr_d__closed__0();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__1() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__1.get(l_Formal_dinstReprOp_drepr_d__closed__1__init)
}

// Lean: Formal.instReprOp.repr._closed_2
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__2: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__2__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b"Formal.Op.close", 15);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__2() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__2.get(l_Formal_dinstReprOp_drepr_d__closed__2__init)
}

// Lean: Formal.instReprOp.repr._closed_3
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__3: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__3__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprOp_drepr_d__closed__2();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__3() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__3.get(l_Formal_dinstReprOp_drepr_d__closed__3__init)
}

// Lean: Formal.instReprOp.repr._closed_4
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__4: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__4__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b"Formal.Op.tick", 14);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__4() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__4.get(l_Formal_dinstReprOp_drepr_d__closed__4__init)
}

// Lean: Formal.instReprOp.repr._closed_5
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__5: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__5__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprOp_drepr_d__closed__4();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__5() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__5.get(l_Formal_dinstReprOp_drepr_d__closed__5__init)
}

// Lean: Formal.instReprOp.repr._closed_6
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__6: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__6__init() -> Obj {
    let x_1: Obj = rt::nat::lean_usize_to_nat(2);
    let x_2: Obj = l_Int_dofNat(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__6() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__6.get(l_Formal_dinstReprOp_drepr_d__closed__6__init)
}

// Lean: Formal.instReprOp.repr._closed_7
// Compiled from: Formal.instReprOp.repr
// Source: lean/Formal/Session.lean:7:12
static C_l_Formal_dinstReprOp_drepr_d__closed__7: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprOp_drepr_d__closed__7__init() -> Obj {
    let x_1: Obj = rt::nat::lean_usize_to_nat(1);
    let x_2: Obj = l_Int_dofNat(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprOp_drepr_d__closed__7() -> Obj {
    C_l_Formal_dinstReprOp_drepr_d__closed__7.get(l_Formal_dinstReprOp_drepr_d__closed__7__init)
}

// Lean: Formal.instReprSess
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_d__closed__0();
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess() -> Obj {
    C_l_Formal_dinstReprSess.get(l_Formal_dinstReprSess__init)
}

// Lean: Formal.instReprSess._closed_0
// Compiled from: Formal.instReprSess
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_d__closed__0: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_d__closed__0__init() -> Obj {
    let x_1: Obj = rt::lean_alloc_closure(l_Formal_dinstReprSess_drepr_d__boxed as *const (), 2, 0);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_d__closed__0() -> Obj {
    C_l_Formal_dinstReprSess_d__closed__0.get(l_Formal_dinstReprSess_d__closed__0__init)
}

// Lean: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
pub(crate) unsafe extern "C" fn l_Formal_dinstReprSess_drepr(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: Obj = l_Formal_dinstReprSess_drepr_d__redArg(x_1);
    return x_3;
}

// Lean: Formal.instReprSess.repr._boxed
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
pub(crate) unsafe extern "C" fn l_Formal_dinstReprSess_drepr_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: Obj = l_Formal_dinstReprSess_drepr(x_1, x_2);
    rt::lean_dec(x_2);
    return x_3;
}

// Lean: Formal.instReprSess.repr._redArg
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
pub(crate) unsafe extern "C" fn l_Formal_dinstReprSess_drepr_d__redArg(x_1: Obj) -> Obj {
    let x_2: u8 = rt::lean_ctor_get_uint8(x_1, ::core::mem::size_of::<usize>());
    let x_3: Obj = rt::lean_ctor_get(x_1, 0);
    let mut x_5: Obj;
    let mut x_6: u8;
    'b4: {
        let x_37: u8 = (!rt::lean_is_exclusive(x_1)) as u8;
        match x_37 {
            0 => {
                x_5 = x_1;
                x_6 = x_37;
                break 'b4;
            }
            _ => {
                rt::lean_inc(x_3);
                rt::lean_dec(x_1);
                x_5 = rt::lean_box(0);
                x_6 = x_37;
                break 'b4;
            }
        }
    }
    let x_7: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5();
    let x_8: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__6();
    let x_9: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__7();
    let x_10: Obj = l_Bool_drepr_d__redArg(x_2);
    let x_11: Obj = rt::lean_alloc_ctor(4, 2, 0);
    rt::lean_ctor_set(x_11, 0, x_9);
    rt::lean_ctor_set(x_11, 1, x_10);
    let x_12: u8 = 0u8;
    let mut x_14: Obj;
    'b13: {
        match x_6 {
            0 => {
                rt::lean_ctor_set_tag(x_5, 6);
                rt::lean_ctor_set(x_5, 0, x_11);
                x_14 = x_5;
                break 'b13;
            }
            _ => {
                let x_36: Obj = rt::lean_alloc_ctor(6, 1, 1);
                rt::lean_ctor_set(x_36, 0, x_11);
                x_14 = x_36;
                break 'b13;
            }
        }
    }
    rt::lean_ctor_set_uint8(x_14, ::core::mem::size_of::<usize>(), x_12);
    let x_15: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_15, 0, x_8);
    rt::lean_ctor_set(x_15, 1, x_14);
    let x_16: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__9();
    let x_17: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_17, 0, x_15);
    rt::lean_ctor_set(x_17, 1, x_16);
    let x_18: Obj = rt::lean_box(1);
    let x_19: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_19, 0, x_17);
    rt::lean_ctor_set(x_19, 1, x_18);
    let x_20: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__11();
    let x_21: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_21, 0, x_19);
    rt::lean_ctor_set(x_21, 1, x_20);
    let x_22: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_22, 0, x_21);
    rt::lean_ctor_set(x_22, 1, x_7);
    let x_23: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__12();
    let x_24: Obj = l_Nat_dreprFast(x_3);
    let x_25: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_25, 0, x_24);
    let x_26: Obj = rt::lean_alloc_ctor(4, 2, 0);
    rt::lean_ctor_set(x_26, 0, x_23);
    rt::lean_ctor_set(x_26, 1, x_25);
    let x_27: Obj = rt::lean_alloc_ctor(6, 1, 1);
    rt::lean_ctor_set(x_27, 0, x_26);
    rt::lean_ctor_set_uint8(x_27, ::core::mem::size_of::<usize>(), x_12);
    let x_28: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_28, 0, x_22);
    rt::lean_ctor_set(x_28, 1, x_27);
    let x_29: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__15();
    let x_30: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__16();
    let x_31: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_31, 0, x_30);
    rt::lean_ctor_set(x_31, 1, x_28);
    let x_32: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__17();
    let x_33: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_33, 0, x_31);
    rt::lean_ctor_set(x_33, 1, x_32);
    let x_34: Obj = rt::lean_alloc_ctor(4, 2, 0);
    rt::lean_ctor_set(x_34, 0, x_29);
    rt::lean_ctor_set(x_34, 1, x_33);
    let x_35: Obj = rt::lean_alloc_ctor(6, 1, 1);
    rt::lean_ctor_set(x_35, 0, x_34);
    rt::lean_ctor_set_uint8(x_35, ::core::mem::size_of::<usize>(), x_12);
    return x_35;
}

// Lean: Formal.instReprSess.repr._redArg._closed_0
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b"{ ", 2);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_1
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__1: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__1__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b"isOpen", 6);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__1() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__1.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__1__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_10
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__10: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__10__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b"count", 5);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__10() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__10.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__10__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_11
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__11: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__11__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__10();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__11() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__11.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__11__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_12
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__12: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__12__init() -> Obj {
    let x_1: Obj = rt::nat::lean_usize_to_nat(9);
    let x_2: Obj = l_Int_dofNat(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__12() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__12.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__12__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_13
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__13: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__13__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b" }", 2);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__13() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__13.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__13__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_14
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__14: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__14__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0();
    let x_2: Obj = l_String_dInternal_dlength(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__14() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__14.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__14__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_15
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__15: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__15__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__14();
    let x_2: Obj = l_Int_dofNat(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__15() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__15.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__15__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_16
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__16: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__16__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__0();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__16() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__16.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__16__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_17
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__17: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__17__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__13();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__17() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__17.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__17__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_2
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__2: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__2__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__1();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__2() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__2.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__2__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_3
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__3: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__3__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__2();
    let x_2: Obj = rt::lean_box(0);
    let x_3: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_3, 0, x_2);
    rt::lean_ctor_set(x_3, 1, x_1);
    return x_3;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__3() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__3.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__3__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_4
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__4: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__4__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b" := ", 4);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__4() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__4.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__4__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_5
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__4();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_6
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__6: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__6__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__5();
    let x_2: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__3();
    let x_3: Obj = rt::lean_alloc_ctor(5, 2, 0);
    rt::lean_ctor_set(x_3, 0, x_2);
    rt::lean_ctor_set(x_3, 1, x_1);
    return x_3;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__6() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__6.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__6__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_7
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__7: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__7__init() -> Obj {
    let x_1: Obj = rt::nat::lean_usize_to_nat(10);
    let x_2: Obj = l_Int_dofNat(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__7() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__7.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__7__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_8
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__8: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__8__init() -> Obj {
    let x_1: Obj = rt::lean_mk_string_unchecked(b",", 1);
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__8() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__8.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__8__init)
}

// Lean: Formal.instReprSess.repr._redArg._closed_9
// Compiled from: Formal.instReprSess.repr
// Source: lean/Formal/Session.lean:12:12
static C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__9: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__9__init() -> Obj {
    let x_1: Obj = l_Formal_dinstReprSess_drepr_d__redArg_d__closed__8();
    let x_2: Obj = rt::lean_alloc_ctor(3, 1, 0);
    rt::lean_ctor_set(x_2, 0, x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_Formal_dinstReprSess_drepr_d__redArg_d__closed__9() -> Obj {
    C_l_Formal_dinstReprSess_drepr_d__redArg_d__closed__9.get(l_Formal_dinstReprSess_drepr_d__redArg_d__closed__9__init)
}

// Lean: Formal.run
// Source: lean/Formal/Session.lean:38:1
pub(crate) unsafe extern "C" fn l_Formal_drun(mut x_1: Obj, mut x_2: Obj) -> Obj {
    'tail: loop {
        match rt::lean_obj_tag(x_1) {
            0 => {
                let x_3: Obj = rt::lean_alloc_ctor(1, 1, 0);
                rt::lean_ctor_set(x_3, 0, x_2);
                return x_3;
            }
            _ => {
                let x_4: Obj = rt::lean_ctor_get(x_1, 0);
                let x_5: Obj = rt::lean_ctor_get(x_1, 1);
                let x_6: u8 = rt::lean_unbox(x_4) as u8;
                let x_7: Obj = l_Formal_dapply(x_6, x_2);
                match rt::lean_obj_tag(x_7) {
                    0 => {
                        return x_7;
                    }
                    _ => {
                        let x_8: Obj = rt::lean_ctor_get(x_7, 0);
                        rt::lean_inc(x_8);
                        rt::lean_dec_ref(x_7);
                        let t_0: Obj = x_5;
                        let t_1: Obj = x_8;
                        x_1 = t_0;
                        x_2 = t_1;
                        continue 'tail;
                    }
                }
            }
        }
    }
}

// Lean: Formal.run._boxed
// Compiled from: Formal.run
// Source: lean/Formal/Session.lean:38:1
pub(crate) unsafe extern "C" fn l_Formal_drun_d__boxed(x_1: Obj, x_2: Obj) -> Obj {
    let x_3: Obj = l_Formal_drun(x_1, x_2);
    rt::lean_dec(x_1);
    return x_3;
}

