// Compiled Lean module Init.Data.List.Basic. Generated by lungo; do not edit.

// Lean: List.range
// Source: <lean>/Init/Data/List/Basic.lean:2092:1
pub(crate) unsafe extern "C" fn l_List_drange(x_1: Obj) -> Obj {
    let x_2: Obj = rt::lean_box(0);
    let x_3: Obj = l_List_drange_dloop(x_1, x_2);
    return x_3;
}

// Lean: List.range.loop
// Source: <lean>/Init/Data/List/Basic.lean:2105:3
pub(crate) unsafe extern "C" fn l_List_drange_dloop(mut x_1: Obj, mut x_2: Obj) -> Obj {
    'tail: loop {
        let x_3: Obj = rt::nat::lean_usize_to_nat(0);
        let x_4: u8 = l_Nat_ddecEq(x_1, x_3);
        match x_4 {
            1 => {
                rt::lean_dec(x_1);
                return x_2;
            }
            _ => {
                let x_5: Obj = rt::nat::lean_usize_to_nat(1);
                let x_6: Obj = l_Nat_dsub(x_1, x_5);
                rt::lean_dec(x_1);
                rt::lean_inc(x_6);
                let x_7: Obj = rt::lean_alloc_ctor(1, 2, 0);
                rt::lean_ctor_set(x_7, 0, x_6);
                rt::lean_ctor_set(x_7, 1, x_2);
                let t_0: Obj = x_6;
                let t_1: Obj = x_7;
                x_1 = t_0;
                x_2 = t_1;
                continue 'tail;
            }
        }
    }
}

// Lean: List.reverse._redArg
// Compiled from: List.reverse
// Source: <lean>/Init/Data/List/Basic.lean:562:1
pub(crate) unsafe extern "C" fn l_List_dreverse_d__redArg(x_1: Obj) -> Obj {
    let x_2: Obj = rt::lean_box(0);
    let x_3: Obj = l_List_dreverseAux_d__redArg(x_1, x_2);
    return x_3;
}

// Lean: List.reverseAux._redArg
// Compiled from: List.reverseAux
// Source: <lean>/Init/Data/List/Basic.lean:554:1
pub(crate) unsafe extern "C" fn l_List_dreverseAux_d__redArg(mut x_1: Obj, mut x_2: Obj) -> Obj {
    'tail: loop {
        match rt::lean_obj_tag(x_1) {
            0 => {
                return x_2;
            }
            _ => {
                let x_3: Obj = rt::lean_ctor_get(x_1, 0);
                let x_4: Obj = rt::lean_ctor_get(x_1, 1);
                let mut x_6: Obj;
                let mut x_7: u8;
                'b5: {
                    let x_12: u8 = (!rt::lean_is_exclusive(x_1)) as u8;
                    match x_12 {
                        0 => {
                            x_6 = x_1;
                            x_7 = x_12;
                            break 'b5;
                        }
                        _ => {
                            rt::lean_inc(x_4);
                            rt::lean_inc(x_3);
                            rt::lean_dec(x_1);
                            x_6 = rt::lean_box(0);
                            x_7 = x_12;
                            break 'b5;
                        }
                    }
                }
                let mut x_9: Obj;
                'b8: {
                    match x_7 {
                        0 => {
                            rt::lean_ctor_set(x_6, 1, x_2);
                            x_9 = x_6;
                            break 'b8;
                        }
                        _ => {
                            let x_11: Obj = rt::lean_alloc_ctor(1, 2, 0);
                            rt::lean_ctor_set(x_11, 0, x_3);
                            rt::lean_ctor_set(x_11, 1, x_2);
                            x_9 = x_11;
                            break 'b8;
                        }
                    }
                }
                let t_0: Obj = x_4;
                let t_1: Obj = x_9;
                x_1 = t_0;
                x_2 = t_1;
                continue 'tail;
            }
        }
    }
}

