// Compiled Lean module Init.Data.String.Bootstrap. Generated by lungo; do not edit.

// Lean: String.Internal.append
// Source: <lean>/Init/Data/String/Bootstrap.lean:77:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_String_dInternal_dappend(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_string_append(x_1, x_2);
    r
}

// Lean: String.Internal.length
// Source: <lean>/Init/Data/String/Bootstrap.lean:70:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_String_dInternal_dlength(x_1: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_string_length(x_1);
    r
}

// Lean: String.push
// Source: <lean>/Init/Data/String/Bootstrap.lean:23:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_String_dpush(x_1: Obj, x_2: u32) -> Obj {
    let r: Obj = rt::intrinsics::lean_string_push(x_1, x_2);
    r
}

