// Compiled Lean module Init.Data.String.Basic. Generated by lungo; do not edit.

// Lean: String.Pos.Raw.get
// Source: <lean>/Init/Data/String/Basic.lean:1877:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_String_dPos_dRaw_dget(x_1: Obj, x_2: Obj) -> u32 {
    let r: u32 = rt::intrinsics::lean_string_utf8_get(x_1, x_2);
    r
}

