// Compiled Lean module Init.Data.String.Defs. Generated by lungo; do not edit.

// Lean: String.append
// Source: <lean>/Init/Data/String/Defs.lean:83:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_String_dappend(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_string_append(x_1, x_2);
    r
}

