// Compiled Lean module Init.Prelude. Generated by lungo; do not edit.

// Lean: Array.getInternalBorrowed
// Source: <lean>/Init/Prelude.lean:3272:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Array_dgetInternalBorrowed(x_1: Obj, x_2: Obj, x_3: Obj, x_4: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_array_fget_borrowed(x_2, x_3);
    r
}

// Lean: Array.mk
// Source: <lean>/Init/Prelude.lean:3210:3
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Array_dmk(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_array_mk(x_2);
    r
}

// Lean: Array.size
// Source: <lean>/Init/Prelude.lean:3259:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Array_dsize(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_array_get_size(x_2);
    r
}

// Lean: ByteArray.size
// Source: <lean>/Init/Prelude.lean:3472:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_ByteArray_dsize(x_1: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_byte_array_size(x_1);
    r
}

// Lean: Nat.add
// Source: <lean>/Init/Prelude.lean:1764:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_dadd(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_nat_add(x_1, x_2);
    r
}

// Lean: Nat.ble
// Source: <lean>/Init/Prelude.lean:1881:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_dble(x_1: Obj, x_2: Obj) -> u8 {
    let r: u8 = rt::intrinsics::lean_nat_dec_le(x_1, x_2);
    r
}

// Lean: Nat.decEq
// Source: <lean>/Init/Prelude.lean:1860:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_ddecEq(x_1: Obj, x_2: Obj) -> u8 {
    let r: u8 = rt::intrinsics::lean_nat_dec_eq(x_1, x_2);
    r
}

// Lean: Nat.decLe
// Source: <lean>/Init/Prelude.lean:2079:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_ddecLe(x_1: Obj, x_2: Obj) -> u8 {
    let r: u8 = rt::intrinsics::lean_nat_dec_le(x_1, x_2);
    r
}

// Lean: Nat.decLt
// Source: <lean>/Init/Prelude.lean:2093:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_ddecLt(x_1: Obj, x_2: Obj) -> u8 {
    let r: u8 = rt::intrinsics::lean_nat_dec_lt(x_1, x_2);
    r
}

// Lean: Nat.div
// Source: <lean>/Init/Prelude.lean:2170:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_ddiv(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_nat_div(x_1, x_2);
    r
}

// Lean: Nat.mod
// Source: <lean>/Init/Prelude.lean:2248:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_dmod(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_nat_mod(x_1, x_2);
    r
}

// Lean: Nat.pow
// Source: <lean>/Init/Prelude.lean:1802:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_dpow(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_nat_pow(x_1, x_2);
    r
}

// Lean: Nat.sub
// Source: <lean>/Init/Prelude.lean:2110:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_Nat_dsub(x_1: Obj, x_2: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_nat_sub(x_1, x_2);
    r
}

// Lean: String.ofList
// Source: <lean>/Init/Prelude.lean:3551:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_String_dofList(x_1: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_string_mk(x_1);
    r
}

// Lean: System.Platform.getNumBits
// Source: <lean>/Init/Prelude.lean:2297:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_System_dPlatform_dgetNumBits(x_1: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_system_platform_nbits(x_1);
    r
}

// Lean: System.Platform.numBits
// Source: <lean>/Init/Prelude.lean:2308:1
static C_l_System_dPlatform_dnumBits: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_System_dPlatform_dnumBits__init() -> Obj {
    let x_1: Obj = l_System_dPlatform_dnumBits_d__closed__0();
    return x_1;
}
#[inline]
pub(crate) unsafe fn l_System_dPlatform_dnumBits() -> Obj {
    C_l_System_dPlatform_dnumBits.get(l_System_dPlatform_dnumBits__init)
}

// Lean: System.Platform.numBits._closed_0
// Compiled from: System.Platform.numBits
// Source: <lean>/Init/Prelude.lean:2308:1
static C_l_System_dPlatform_dnumBits_d__closed__0: rt::LazyObj = rt::LazyObj::new();
unsafe fn l_System_dPlatform_dnumBits_d__closed__0__init() -> Obj {
    let x_1: Obj = rt::lean_box(0);
    let x_2: Obj = l_System_dPlatform_dgetNumBits(x_1);
    return x_2;
}
#[inline]
pub(crate) unsafe fn l_System_dPlatform_dnumBits_d__closed__0() -> Obj {
    C_l_System_dPlatform_dnumBits_d__closed__0.get(l_System_dPlatform_dnumBits_d__closed__0__init)
}

// Lean: UInt32.decLe
// Source: <lean>/Init/Prelude.lean:2693:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_UInt32_ddecLe(x_1: u32, x_2: u32) -> u8 {
    let r: u8 = rt::intrinsics::lean_uint32_dec_le(x_1, x_2);
    r
}

// Lean: UInt32.toNat
// Source: <lean>/Init/Prelude.lean:2641:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_UInt32_dtoNat(x_1: u32) -> Obj {
    let r: Obj = rt::intrinsics::lean_uint32_to_nat(x_1);
    r
}

// Lean: USize.ofNatLT
// Source: <lean>/Init/Prelude.lean:2807:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_USize_dofNatLT(x_1: Obj, x_2: Obj) -> usize {
    let r: usize = rt::intrinsics::lean_usize_of_nat(x_1);
    r
}

// Lean: panicCore
// Source: <lean>/Init/Prelude.lean:3696:1
#[inline(always)]
pub(crate) unsafe extern "C" fn l_panicCore(x_1: Obj, x_2: Obj, x_3: Obj) -> Obj {
    let r: Obj = rt::intrinsics::lean_panic_fn_borrowed(x_2, x_3);
    r
}

