[package]
name = "lungo-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The Rust backend: Bridge IR to Rust. An internal part of lungo: depend on `lungo` and `lungo-build`."

[dependencies]
lungo-bir.workspace = true
lungo-protocol.workspace = true
lungo-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
